python/aws_lambda_powertools/logging/logger.py
python/tests/functional/test_aws_lambda_logging.py

*Issue #, if available:* https://github.com/awslabs/aws-lambda-powertools/issues/2
* Fix logging import to use the vended version in aws_lambda_powertools.logging.aws_lambda_logging
* Fix test cases to use the vended version instead
* Remove test cases that cover aws_lambda_logging.wrap as wrap is not present in the vended version

Fix logging import

---

docs/gatsby-config.js

Signed-off-by: heitorlessa <lessa@amazon.co.uk>
*Issue #, if available:* #37
This completes the docs experience by including a search for both docs, and API docs.

Add Algolia search for docs and API reference

---

docs/gatsby-config.js

Signed-off-by: heitorlessa <lessa@amazon.co.uk>
*Issue #, if available:*

[Sync master] feat: add algolia search for docs and api ref (#39)

---

CHANGELOG.md

*Issue #, if available:* #46 
*Description of changes:* Updated CHANGELOG to use [KeepAChangelog standard](https://keepachangelog.com/en/1.0.0/). 

chore: reformat changelog to follow KeepAChangelog standard

---

aws_lambda_powertools/metrics/base.py
tests/functional/test_metrics.py

*Issue #, if available:* #51 
*Description of changes:* If non-string values are passed to add_dimension, cast them to str. 

fix: cast dimension value to str to avoid issue where EMF silently fails

---

aws_lambda_powertools/helper/models.py
aws_lambda_powertools/logging/logger.py
tests/functional/test_logger.py

Fix Logger value coercion to main keys

---

.github/workflows/python_build.yml
Makefile

> One or two sentences as a summary of what's being changed

feat: add codecov service

---

aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/metrics/metric.py
aws_lambda_powertools/metrics/metrics.py
docs/content/core/metrics.mdx
docs/content/index.mdx
example/README.md
example/template.yaml
tests/functional/test_metrics.py

**Issue #, if available:** #61 
>  Changes behavior introduced in #60: Service name passed to metrics constructor (or `POWERTOOLS_SERVICE_NAME` env var) will be used to create a service dimension rather than setting the namespace. Namespace can be set using the `namespace` parameter in Metrics constructor, or `POWERTOOLS_METRICS_NAMESPACE` env var. 

improv: Better namespace/dimension handling for Metrics

---

Makefile

> Makefile had 2 targets: docs-dev (which ran the gatsby docs site locally) and dev-docs (which installs required packages for docs build). Renamed the former to better represent what it does.

chore: rename Makefile target docs-dev to docs-local

---

example/README.md
example/tests/test_handler.py
poetry.lock
pyproject.toml
pytest.ini

> Update pytest config to run example tests. Update tests in example/tests to specify env vars as fixture without requiring user to pass them at runtime.

improv: include example tests in `make tests`

---

.github/workflows/publish.yml

> One or two sentences as a summary of what's being changed
**Manual activities**
1. Document human readable changes in CHANGELOG
2. Bump package version using poetry version <major|minor|patch|specific version>
3. Create a PR to develop branch, and merge if all tests pass
4. Edit the current draft release notes
5. If not already set, use `v<new version>` as a tag, and select develop as target branch
**Automated activities**
1. Extract release notes tag that was published
2. Ensure release notes tag match what's in CHANGELOG and pyproject
3. Run tests, linting, security and complexity base line
4. Publish package to PyPi test repository
5. Publish package to PyPi prod repository
6. Push latest release source code to master using release title as the commit …

feat: automate publishing to pypi

---

aws_lambda_powertools/metrics/metrics.py
docs/content/core/metrics.mdx
tests/functional/test_metrics.py

This feature allows capturing cold start as a metric with an optional param in `log_metrics`. It also adds an additional dimension named `function_name` .
```python
from aws_lambda_powertools.metrics import Metrics, MetricUnit
metrics = Metrics(service="ExampleService")
@metrics.log_metrics(capture_cold_start_metric=True)
def lambda_handler(evt, ctx):
...
```

feat: add capture_cold_start_metric for log_metrics

---

CHANGELOG.md
aws_lambda_powertools/metrics/base.py
pyproject.toml

> Minor version bump to 0.10.0

chore: version bump

---

.github/workflows/publish.yml

> Fix github workflow to push to pypi

fix: correct env var name for publish to pypi test

---

aws_lambda_powertools/metrics/metrics.py
docs/content/core/metrics.mdx
tests/functional/test_metrics.py

> Change default behavior for log_metrics decorator: no longer throws exception if no metrics are emitted during the wrapped function's execution. Added parameter to revert this behavior if exception is desired in this case.

feat: improve error handling for log_metrics decorator

---

docs/src/styles/global.css

Code text were bright and difficult to read - This PR follows WACG contrast ratio to fix that.
Before
After

docs: fix major WCAG contrast issues

---

aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/metrics/metrics.py
tests/functional/test_metrics.py

**Issue #, if available:** #75 
> Change Metrics code to add default "service" dimension when metrics are serialized, rather than just when Metrics is initialized.

fix: metrics default dimension creation

---

aws_lambda_powertools/helper/__init__.py
aws_lambda_powertools/helper/models.py
aws_lambda_powertools/logging/__init__.py
aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/lambda_context.py
aws_lambda_powertools/logging/logger.py
aws_lambda_powertools/metrics/__init__.py
aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/metrics/exceptions.py
aws_lambda_powertools/metrics/metric.py
tests/functional/test_logger.py
tests/functional/test_metrics.py

chore: remove deprecated code before GA

---

CHANGELOG.md
README.md
pyproject.toml

chore: bump to 1.0.0 GA

---

CHANGELOG.md
aws_lambda_powertools/logging/logger.py
pyproject.toml
tests/functional/test_logger.py

**Issue #, if available:** #85 
**Bugfix for #85**
This ensures that when `structure_logs` is used before `inject_lambda_context` it'll have both keys. This can happen in two situations:
1) When a customer uses a custom middleware and reuses `inject_lambda_context` as described in #85
2) Use `structure_logs` in the global scope
**Checklist**

fix: append structured logs when injecting lambda context 

---

pyproject.toml

**Issue #, if available:** #88 
Bumped the dependency selection for the aws-xray-sdk
**Checklist**

chore: support aws-xray-sdk >=2.5.0 till <3.0.0

---

CHANGELOG.md
README.md
poetry.lock
pyproject.toml

**Issue**: #88 
**Description**: Correct dependency locking for X-Ray as Powertools is compatible with all minor versions not just 2.5.0

chore: bump to 1.0.2

---

CHANGELOG.md
aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/logger.py
docs/content/core/logger.mdx
tests/functional/test_aws_lambda_logging.py
tests/functional/test_logger.py
tests/functional/utility_functions.py

**Issue #, if available:** #97 
This addresses a common issue when trying to use `Logger` across multiple modules while wanting to:
* **Create a new child Logger** to inherit parent Logger's configuration (handler, formatter, custom keys, sampling)
* **Reuse the same Logger**, where Logger is enriched iteratively across the code base
For this, we've introduced a new parameter, `child`, when initializing a new Logger, and some internal changes while keeping the same UX and backwards compatibility.
* **[Internal]** Direct access to methods, handlers, etc work as before, except that we proxy properties access to `._logger`
**Key aspects**:
* We support logging inheritance via the `child` parameter, and the `Logger` will be named after `<service>.<caller_file_name>`
* Calling `Logger` with …

feat: logger inheritance

---

aws_lambda_powertools/logging/logger.py
tests/functional/test_logger.py

**Issue #, if available:** #104 
**Checklist**

fix: regression 104 and revert docstring

---

CHANGELOG.md
docs/content/core/tracer.mdx

**Issue #, if available:** #108 
Clarifies `auto_patch=False` feature when reusing Tracer across multiple modules, or in Lambda Layers, where import order creates a side effect where no modules end up being patched.
**Checklist**

docs: clarify Tracer auto_patch as per #108

---

CHANGELOG.md
aws_lambda_powertools/logging/logger.py
tests/functional/test_logger.py

**Issue #, if available:** #107 
**Problem summary**:  PyCharm does not infer from proxied objects when building autocomplete. This means #99 broke autocomplete feature in PyCharm but not in VSCode.
This PR re-adds sub-classing for Logger, and an additional test to cover log statement `location` key.
**Checklist**

improv: logger autocomplete for PyCharm

---

CHANGELOG.md
aws_lambda_powertools/logging/logger.py
tests/functional/test_logger.py

**Issue #, if available:** #115 
**Checklist**

fix: remove root logger handler set by Lambda #115

---

aws_lambda_powertools/tracing/tracer.py
docs/content/core/tracer.mdx
example/tests/test_handler.py
tests/functional/test_tracing.py
tests/unit/test_tracing.py

**Issue #, if available:** #112 
Added checks to capture_method to test if decorated function is a generator (and/or a context manager) and handle those cases appropriately.
**Checklist**

feat: add support for tracing of generators using capture_method decorator

---

aws_lambda_powertools/logging/formatter.py
tests/functional/test_aws_lambda_logging.py

Currently given a custom `json_default` with the Logger When we log out message Then we include the `json_default` in the log message:
```python3
>>> logger = Logger(level="DEBUG", stream=stdout, json_default=lambda o: f"<non-serializable: {type(o).__name__}>")
>>> logger.debug({"x": Unserializable()})
{'timestamp': '2020-08-25 11:55:27,114', 'level': 'DEBUG', 'location': 'test:112', 'service': 'service_undefined', 'sampling_rate': 0.0, 'json_default': '<non-serializable: function>', 'message': {'x': '<non-serializable: Unserializable>'}}
```
The output should exclude `json_default`:
```python3
>>> logger = Logger(level="DEBUG", stream=stdout, json_default=lambda o: f"<non-serializable: {type(o).__name__}>")
>>> logger.debug({"x": Unserializable()}) …
```

fix(logging): Don't include `json_default` in logs

---

docs/content/core/logger.mdx

Correct Documentation on log sampling
**Checklist**

docs: fix log sampling percentage wording

---

README.md

Corrected opening "Lambda Functions" to "Lambda functions"
**Checklist**

docs: minor edit to letter case

---

docs/content/index.mdx
docs/gatsby-config.js
docs/package.json

Corrected opening "Lambda Functions" to "Lambda functions"
**Checklist**

docs: minor edit to letter case part 2

---

aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/logger.py
tests/functional/test_aws_lambda_logging.py

**Issue #, if available:** #138 and #143
> **NOTE:** `sampling_rate` and `service` can not be suppressed
Ensure that the initial key seq is: `level,location,message,timestamp` so by default messages in Cloudwatch logs are easier to read:
```python3
>>> logger = Logger()
>>> logger.info("Eggs")
{'level': 'INFO', 'location': 'method_name:126', 'message': 'Eggs', 'timestamp': '2020-08-27 15:32:51,285', 'service': 'app', 'sampling_rate': 0.0}
```
Also allow for reordering override via `format_keys`
```python3
>>> logger = Logger(format_keys=["message"])
>>> logger.info("Foo")
{'message': 'Message', 'level': 'INFO', 'location': 'method_name:139', 'timestamp': '2020-08-27 15:36:11,494', 'service': 'app', 'sampling_rate': 0.0}
```
You can also suppress `timestamp` or `location` fields by passing …

feat(logger): customizing logger output

---

docs/content/core/logger.mdx
docs/content/core/metrics.mdx
tests/functional/test_aws_lambda_logging.py

**Issue #, if available:** #143 
This creates a new section to address common concerns customers migrating from Python Logging or other libraries to Powertools Logger:
**Checklist**

docs: new section "Migrating from other Loggers"

---

aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/logger.py
docs/content/core/logger.mdx
tests/functional/test_aws_lambda_logging.py

**Issue #, if available:** #137 
When X-Ray is enabled, Logger will include a `xray_trace_id` key with the value of the Trace ID captured from the environment.
**UPDATE**: Given X-Ray Trace ID will change on a per invocation we cannot support changing the order of `xray_trace_id`. If you don't enable X-Ray this will key only appear.
**When enabled**
```json
{
"level": "INFO",
"location": "<module>:7",
"message": "Testing x-ray id...",
"timestamp": "2020-08-30 17:03:12,653",
"service": "blah",
"sampling_rate": 0.0,
"xray_trace_id": "1-5759e988-bd862e3fe1be46a994272793"
}
```
**Checklist**

feat: add xray_trace_id key when tracing is active #137

---

CONTRIBUTING.md

Add a troubleshooting section in the CONTRIBUTING.md
**Checklist**

docs: add troubleshooting section

---

aws_lambda_powertools/utilities/batch/__init__.py
aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/batch/middlewares.py
aws_lambda_powertools/utilities/batch/sqs.py
aws_lambda_powertools/utilities/parameters/secrets.py
docs/content/index.mdx
docs/content/utilities/batch.mdx
docs/gatsby-config.js
tests/functional/test_utilities_batch.py
tests/unit/test_utilities_batch.py

#92 : SQS Partial batch
Hi everyone ! Here's a **very initial** design proposal to work with batches. This draft intends to work as our communication channel to hear your toughts. Before putting more effort in everything that's missing (docs, tests, typing, etc)  I look forward hearing opinions from issue's participants: @heitorlessa , @nmoutschen , @Nr18 .
**Checklist**
* [-] Update tests
* [-] Update docs

feat: SQS Partial failure

---

.pre-commit-config.yaml
aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/utilities/batch/sqs.py
docs/content/utilities/batch.mdx
example/hello_world/app.py

Changes:
* Fix some of the type hints
* Add messing docstrings for parameters
* Fix typos
**Checklist**

chore: fix typos, docstrings and type hints

---

aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/typing/lambda_cognito_identity.py
aws_lambda_powertools/utilities/typing/lambda_context.py
docs/content/utilities/batch.mdx
tests/functional/test_utilities_typing.py

Changes:
* base.py - `records` can't just be iterable as we reference it by `__getitem__`
* base.py - logger.debugger is expecting a `%s`
* docs - Typos in the docs
* formatter.py - `_build_root_keys` can be a static method
* typing - add some missing unit tests
**Checklist**

chore(batch): Housekeeping for recent changes

---

CHANGELOG.md
pyproject.toml

chore: bump version to 1.5.0

---

CHANGELOG.md
aws_lambda_powertools/metrics/base.py
tests/functional/test_metrics.py

**Issue #, if available:** #165 
Update metrics utility to support multiple values for the same metric name. 
**Checklist**

feat: emf multiple metric values

---

aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/utilities/data_classes/alb_event.py
aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
tests/functional/validator/test_validator.py

Changes:
* validator - Add test for the validator decator with an envelope
* data_classes - Call DictWrapper constructor with the nested dict
* metrics - Some minor type hint improvements
**Checklist**
---

fix: add missing tests, correct calls to DictWrapper constructor and improve metrics type hints

---

aws_lambda_powertools/utilities/batch/sqs.py
tests/functional/test_utilities_batch.py

**Issue #, if available:** #169 
**Checklist**

fix: remove DeleteMessageBatch call to SQS api if there are no messages to delete

---

aws_lambda_powertools/tracing/tracer.py
tests/functional/test_tracing.py

Disable tracer when using the Chalice CLI.  This enables customers to run `chalice deploy`, `chalice local`, and other Chalice CLI commands without having to explicitly disable the tracer.
**Checklist**

improv: disable tracer when using the Chalice CLI

---

docs/content/core/logger.mdx
docs/content/core/metrics.mdx
docs/src/gatsby-theme-apollo-core/components/flex-wrapper.js
docs/src/styles/global.css

**Issue #, if available:** #161 
**Checklist**

docs: add testing tips, increase content width, and improve log sampling wording

---

aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py

It seems that when accessing boolean value from dynamodb index name `bool` is used instead of correct one `BOOL`.
Have a look at https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html to see list of available attribute values
**Checklist**

fix: accessing boolean value in dynamodb utility class

---

docs/package-lock.json
docs/package.json

This directly updates a transitive dependency `node-forge`, and also upgrades amplify, ant, and gatsby plugins.
The only one we cannot fix ourselves is `bl` as discussed in: https://github.com/apollographql/gatsby-theme-apollo/issues/127
**Checklist**

chore: docs npm security node-forge

---

aws_lambda_powertools/utilities/advanced_parser/envelopes/base.py
aws_lambda_powertools/utilities/advanced_parser/envelopes/dynamodb.py
aws_lambda_powertools/utilities/advanced_parser/schemas/dynamodb.py
aws_lambda_powertools/utilities/advanced_parser/schemas/sqs.py
tests/functional/parser/test_dynamodb.py
tests/functional/parser/test_eventbridge.py
tests/functional/parser/test_sqs.py
tests/functional/parser/utils.py

* Make some methods static
* Run code formatter
* Some lint based changes
* Add missing test cases
**Checklist**

test(parser): Add missing test coverage and lint changes

---

aws_lambda_powertools/utilities/data_classes/common.py
tests/functional/test_lambda_trigger_events.py

#185
Update BaseProxyEvent `get_header_value` method to be case insensitive
by default and add a flag for case sensitive lookups
**Checklist**

feat(data_classes): case insensitive header lookup

---

README.md

Clarified python focus and added cross-reference to Java.
n/a
Clarified that the repo is focused on Python and added a cross-reference to the Java implementation.
**Checklist**

improv: Update README.md

---

aws_lambda_powertools/logging/filters.py
aws_lambda_powertools/logging/logger.py
tests/functional/test_logger.py

**Issue #, if available:** #194
This PR adds a log filter in the root logger to reject any log record coming from our Logger - This will prevent child logger to propagate log records to their parents as well as root loggers leading to duplicated log entries.
This unblocks issue described in 194 when customers assume root logger to be configured as per Lambda docs.
**Checklist**

improv: add log filter in root handler to prevent child log records duplication

---

docs/content/core/logger.mdx

**Issue #, if available:** #195 
This PR changes Logger's example where a conditional key was added but not removed if it wasn't present in subsequent invocation - Based on #195, this provides a safer example, and a note as to why it is so.
**Checklist**

docs: add more info on conditional keys #195

---

aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
tests/events/apiGatewayProxyV2IamEvent.json
tests/events/apiGatewayProxyV2LambdaAuthorizerEvent.json
tests/functional/test_lambda_trigger_events.py

Update to support IAM and Lambda authorizer for API
Gateway V2 trigger events
**Checklist**

feat(data_classes): API Gateway V2 IAM and Lambda

---

docs/content/index.mdx

**Issue #, if available:** #203 
Added the necessary permission one need to add to he IAM policy in order to use the powertools layer. 
**Checklist**

docs: add minimal permission set for using layer

---

docs/content/core/logger.mdx

- add instructions on how you could enable `botocore` and `boto3` logs
**Checklist**

docs: add faq section

---

aws_lambda_powertools/utilities/parser/envelopes/__init__.py
aws_lambda_powertools/utilities/parser/envelopes/sns.py
aws_lambda_powertools/utilities/parser/models/__init__.py
aws_lambda_powertools/utilities/parser/models/sns.py
tests/events/snsEvent.json
tests/functional/parser/schemas.py
tests/functional/parser/test_sns.py
tests/functional/test_lambda_trigger_events.py
tests/functional/validator/conftest.py

feat: Add sns notification support to Parser utility #206

---

docs/content/utilities/data_classes.mdx

**Issue #, if available:** #208
**Checklist**

docs: correct example usage of SES data class

---

aws_lambda_powertools/utilities/data_classes/event_bridge_event.py
aws_lambda_powertools/utilities/parser/models/event_bridge.py
tests/events/eventBridgeEvent.json
tests/functional/parser/test_eventbridge.py
tests/functional/test_lambda_trigger_events.py

New EventBridge Replay feature introduces a new optional field `replay-name`: https://aws.amazon.com/blogs/aws/new-archive-and-replay-events-with-amazon-eventbridge/
This PR adds support for it in both data_classes and parser as `replay_name`.
**Checklist**

feat: include new EventBridge replay-name field in parser and data_classes utilities

---

CHANGELOG.md
pyproject.toml

chore: bump to 1.8.0

---

aws_lambda_powertools/utilities/parser/models/__init__.py
aws_lambda_powertools/utilities/parser/models/ses.py
poetry.lock
pyproject.toml
tests/functional/parser/test_ses.py

Also added email-validator module as an extra dependancy for pydantic email addresses validations.

feat: Add Ses lambda event support to Parser utility #213

---

docs/content/core/logger.mdx

Add clarification on the documents around Log keys that cannot be suppressed
Issue #217 , re: #215
Added document reference about Logger keys that cannot be suppressed in the Log output.
**Checklist**

docs: Clarify Logger keys that cannot be suppressed

---

docs/src/gatsby-theme-apollo-docs/components/page-content.js

docs: fix broken link for github

---

aws_lambda_powertools/utilities/parser/models/__init__.py
aws_lambda_powertools/utilities/parser/models/alb.py
docs/content/utilities/parser.mdx
tests/functional/parser/test_alb.py

feat: Add alb lambda event support to Parser utility #228

feat: Add alb lambda event support to Parser utility

---

aws_lambda_powertools/utilities/parser/envelopes/__init__.py
aws_lambda_powertools/utilities/parser/envelopes/cloudwatch.py
aws_lambda_powertools/utilities/parser/models/__init__.py
aws_lambda_powertools/utilities/parser/models/cloudwatch.py
docs/content/utilities/parser.mdx
tests/functional/parser/schemas.py
tests/functional/parser/test_cloudwatch.py

feat: Add cloudwatch lambda event support to Parser utility

---

aws_lambda_powertools/utilities/parser/envelopes/__init__.py
aws_lambda_powertools/utilities/parser/envelopes/kinesis.py
aws_lambda_powertools/utilities/parser/models/__init__.py
aws_lambda_powertools/utilities/parser/models/kinesis.py
docs/content/utilities/parser.mdx
tests/functional/parser/schemas.py
tests/functional/parser/test_kinesis.py

feat: Add Kinesis lambda event support to Parser utility #226 
This adds automatic base64 decode in the schema.

feat: Add Kinesis lambda event support to Parser utility

---

tests/events/s3EventDecodedKey.json
tests/functional/parser/test_cloudwatch.py
tests/functional/test_lambda_trigger_events.py
tests/unit/test_tracing.py

Changes:
* Add missing fail case for cloudwatch parsing
* Add more test data for decoding s3 object keys
* Update data_classes test to include the new event json examples
* Fix class naming to be CamelCase
**Checklist**

test(general): Add missing tests for parser

---

aws_lambda_powertools/utilities/data_classes/common.py

This change is to allow easier testing of data classes by adding an __eq__ function to the base DictWrapper class. This new function will check the equality of the data contained in the object opposed to the memory location.
**Checklist**

improv: Added __eq__ function to DictWrapper for better equality checks

---

tests/functional/test_lambda_trigger_events.py

**Issue #, if available:** #233
Added a equals test to  test the `__eq__` method.
**Checklist**

test: DictWrapper equals method

---

pyproject.toml

#221:
Add `py.typed` into package folder and include into `pyproject.toml`.
**Checklist**
* [-] Update tests
* [-] Update docs

feat: PEP-561 compliance

---

CHANGELOG.md
docs/content/core/tracer.mdx

**Issue #, if available:** #238 
Added clarification to Tracer docs for `capture_method` decorator, and how it can cause function responses to be read earlier than expected. This addresses potentially unexpected behaviours where functions return objects where reading the function response causes side-effects, such as file-like objects or the botocore `StreamingBody`. 
**Checklist**

docs: add clarification to Tracer docs for `capture_method`

---

Makefile

From the manual of make
> A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request. There are two reasons to use a phony target: to avoid a conflict with a file of the same name, and to improve performance.
See: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
**Checklist**

chore: implement phony targets correctly

---

CHANGELOG.md
aws_lambda_powertools/logging/logger.py
tests/functional/test_aws_lambda_logging.py
tests/functional/test_logger.py

**Issue #, if available:** #249
* Adds `init` attribute to parent Loggers to verify whether they've been previously configured
* Updates tests to ensure all `service_name` is unique
* Ensures there is only one test that doesn't define `service_name`
**Checklist**

fix: prevent touching preconfigured loggers #249

---

CHANGELOG.md
pyproject.toml

chore: bump to 1.9.1

---

docs/package.json
docs/yarn.lock

chore: docs npm high vuln.

---

aws_lambda_powertools/utilities/validation/base.py
aws_lambda_powertools/utilities/validation/validator.py
docs/content/utilities/validation.mdx
tests/functional/validator/conftest.py
tests/functional/validator/test_validator.py

Issue #246 
Pass formats dict through to fastjsonschema
**Checklist**

feat: support custom formats in JSON Schema validation

---

aws_lambda_powertools/logging/filters.py
aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/logger.py
aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/tracing/tracer.py
aws_lambda_powertools/utilities/parameters/dynamodb.py
aws_lambda_powertools/utilities/parser/envelopes/cloudwatch.py
aws_lambda_powertools/utilities/parser/envelopes/dynamodb.py
aws_lambda_powertools/utilities/parser/envelopes/kinesis.py
aws_lambda_powertools/utilities/parser/envelopes/sns.py
aws_lambda_powertools/utilities/parser/envelopes/sqs.py

* Use simplified logic checks
* Use list and dict comprehension
* Remove useless assignments and return value immediately 
**Checklist**

chore: general simplifications and cleanup

---

aws_lambda_powertools/logging/formatter.py
docs/content/core/logger.mdx
tests/functional/test_logger.py

**Issue #, if available:** #253
This PR adds support for extra parameter when logging messages across all levels. Any key/value added using `extra` parameter will be at the root level of the structured log.
Before this PR, all fields added in `extra` parameter are discarded when structuring logs.
**Add request_id field while logging a message**
```python
logger = Logger(service="payment")
fields = { "request_id": "1123" }
logger.info("Hello", extra=fields)
```
```json
{
"level": "INFO",
"location": "<module>:5",
"message": "Hello",
"timestamp": "2021-01-12 14:08:12,357",
"service": "payment",
"sampling_rate": 0.0,
"request_id": "1123"
}
```
**Q: What's the difference between `structure_log` and `extra` after this PR?**
Keys added with `structure_log` will persist across multiple log …

feat: support extra parameter in Logger messages

---

docs/content/index.mdx

**Issue #, if available:** #210
We have now an additional layer with extra dependencies such as `pydantic` that you need for the validation feature. Keep in mind that the size of the extras layer is ~155MB unzipped. 
**Checklist**

docs: add info about extras layer

---

aws_lambda_powertools/utilities/parameters/__init__.py
aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/base.py
docs/content/utilities/parameters.mdx
tests/functional/test_utilities_parameters.py

#187 
this is a poc for the app conf provider.
there's a lot of work in the docs department and in the tests.
There's just one test at the moment but it works. 
There's also the issue of handling yaml confs. This might require a new transform with pyyaml package maybe.
Is the UX ok?

feat: Add AppConfig parameter provider

---

docs/content/utilities/data_classes.mdx

This PR fixes an import statement in the documentation.
**Checklist**

docs: fix import

---

CHANGELOG.md
docs/content/utilities/parameters.mdx
pyproject.toml

chore: bump to 1.10.0

---

aws_lambda_powertools/utilities/parser/envelopes/__init__.py
aws_lambda_powertools/utilities/parser/envelopes/sns.py
aws_lambda_powertools/utilities/parser/models/sns.py
docs/content/utilities/parser.mdx
tests/events/snsSqsEvent.json
tests/functional/parser/test_sns.py

**Issue #, if available:** #265
When using SNS -> SQS -> Lambda, the SNS payload differs from SNS -> Lambda. It's not explicitly documented as per #262 - This information is available on per Target protocol, and Lambda is the only one that seems to differ from others (e.g. SQS, HTTP, etc.)
This PR does the following:
* Adjusts `MessageAttributes` to be an optional field
* Dynamically adjusts `UnsubscribeURL -> UnsubscribeUrl`, and `SigningCertURL -> SigningCertUrl` to make backwards compatible
* Creates a new envelope `SnsSqsEnvelope` to make this process seamless for customers
> **UX**
Excerpt from tests, where customers can continue to write their parsing as before, but use a new **envelopes.SnsSqsEnvelope** to correctly extract the original SNS payload that was doubled marshalled too. …

feat: add support for SNS->SQS protocol

---

aws_lambda_powertools/utilities/parameters/appconfig.py

Use correct import for docstring 
**Checklist**

docs(appconfig): Use correct import for docstring

---

docs/package.json
docs/yarn.lock

chore: fix immer and socket.io CVEs

---

aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/batch/exceptions.py
aws_lambda_powertools/utilities/batch/sqs.py
tests/functional/test_utilities_batch.py
tests/unit/test_utilities_batch.py

**Issue #, if available:** #275
Update batch exception handling to include more detail of the actual exceptions raised in users processing code.
_Why not just log the exception one-by-one as we catch them?_
By default, the aws_lambda_powertools package logger is suppressed. Logging from package modules would require users to take [additional steps](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode) to see those logs.
**Checklist**

fix: batch processing exceptions

---

CHANGELOG.md
aws_lambda_powertools/utilities/parser/models/dynamodb.py
aws_lambda_powertools/utilities/parser/models/kinesis.py
aws_lambda_powertools/utilities/parser/models/s3.py
aws_lambda_powertools/utilities/parser/models/ses.py
aws_lambda_powertools/utilities/parser/models/sns.py
aws_lambda_powertools/utilities/parser/models/sqs.py
aws_lambda_powertools/utilities/parser/types.py
pyproject.toml
tests/functional/parser/schemas.py

**Issue #280**
1. Added if block to know if typing_extensions should be imported based on the python version.
if python >= 3.8 typing extensions will not be imported and the native implementation will be used
else will try to import typing_extensions and catch the ImportError
2. Updated modules which imported this dependency.
3. Updated pyproject.toml to only install typing-extensions when python version is <3.8
**Checklist**

fix: remove unnecessary typing-extensions for py3.8

---

aws_lambda_powertools/tracing/tracer.py

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-python/issues/283
Disable batching of X-Ray subsegments, thus preventing an issue where the total data sent in one go to the X-Ray daemon is too large and causes a "Message too long" error.
**Checklist**

fix: disable batching of X-Ray subsegments

---

aws_lambda_powertools/utilities/parser/envelopes/base.py
aws_lambda_powertools/utilities/parser/envelopes/cloudwatch.py
aws_lambda_powertools/utilities/parser/envelopes/dynamodb.py
aws_lambda_powertools/utilities/parser/envelopes/event_bridge.py
aws_lambda_powertools/utilities/parser/envelopes/kinesis.py
aws_lambda_powertools/utilities/parser/envelopes/sns.py
aws_lambda_powertools/utilities/parser/envelopes/sqs.py

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-python/issues/285
Change the type hinting signature for `aws_lambda_powertools.utilities.parser.envelopes.*Envelope`
**Checklist**

fix: fix typing hit for envelope parse model

---

.github/labeler.yml

Update to the correct location of `docs/*` for the documentation labels
**Checklist**

chore: Correct the docs location for the labeller

---

docs/utilities/data_classes.md

Anchors casing need to match what is generated in the html, which is lower case.
eg: `S3` should be `s3`
> **NOTE:** This does not fix the anchor links on the logger.md as the toc level is 3, and no anchor tags are generated for the following
```markdown
[Service parameter](#the-service-parameter), [Inheriting Loggers](#inheriting-loggers), [Overriding Log records](#overriding-log-records), and [Logging exceptions](#logging-exceptions)
```
mkdocs.yml
```yml
- toc:
permalink: true
toc_depth: 3
```
**Checklist**

docs(data-classes): Fix anchor tags to be lower case

---

aws_lambda_powertools/utilities/idempotency/persistence/base.py
docs/utilities/idempotency.md
tests/functional/idempotency/test_idempotency.py
tests/unit/test_json_encoder.py

This fixes an issue with caching in the unreleased idempotency util. We were mistakenly caching in progress records, meaning execution environments could get "stuck" with in progress records in the cache. Records in this state shouldn't be included in the cache, as we've no way to reflect changes from outside the execution environment in the local caches.
**Checklist**

fix: correct behaviour to avoid caching "INPROGRESS" records

---

docs/utilities/data_classes.md

#298
Correct import for DynamoDBRecordEventName, should be: 
```python3
from aws_lambda_powertools.utilities.data_classes.dynamo_db_stream_event import DynamoDBStreamEvent, DynamoDBRecordEventName
```
**Checklist**

docs(data-classes): Correct import for DynamoDBRecordEventName

---

aws_lambda_powertools/shared/cache_dict.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
tests/functional/idempotency/test_idempotency.py
tests/unit/test_lru_cache.py

Fix a KeyError when we an error happens and local_cache is True and the cache is empty
Current fix is either check `idempotency_key` exists in cache before calling `del`:
```python3
if idempotency_key in self._cache:
del self._cache[idempotency_key]
```
> NOTE: `pop` causes a KeyError when there is a match based on the current `LRUDict` implementation.
```python3
self._cache.pop(idempotency_key, None)
```
**Alternative** fix is to change the `LRUDict` to only expose the `get`, `__getitem__` and `__setitem__`. And when
setting an `idempotency_key` move it up for eviction
```python3
self._cache[idempotency_key] = None
```
**Checklist**

feat(idempotency): Fix KeyError when local_cache is True and an error is raised in the lambda handler

---

docs/utilities/idempotency.md

Changes:
* Used the same formatting and indentation for all of the code examples
* Fix various typos and spelling
* Highlight the correct lines on some of the examples
**Checklist**

docs(idempotent): Fix typos and code formatting

---

docs/utilities/data_classes.md

docs(dataclasses): new Connect Contact Flow

---

CHANGELOG.md
pyproject.toml

chore: bump 1.11.0

---

README.md
docs/utilities/idempotency.md

Changes:
* Removed accidentally checked in example file
* Correct some examples in the codes
* Correct the documented defaults for `local_cache_max_items` in  IdempotencyConfig
* Correct the highlighted lines in the examples
* Correct formatting for `Advanced` title
* Add link to idempontency docs from the Readme
**Checklist**

docs(idempotency): Correct examples and line highlights

---

aws_lambda_powertools/utilities/idempotency/idempotency.py
tests/functional/idempotency/test_idempotency.py

GIVEN a miss configured persistence layer
like no table was created for the idempotency persistence layer
WHEN handling the idempotent call
AND save_inprogress raises a ClientError
THEN idempotent should raise an IdempotencyPersistenceLayerError
**Checklist**

fix(idempotency): Correctly handle save_inprogress errors

---

aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/metrics/metric.py
aws_lambda_powertools/metrics/metrics.py

Correct some of the code examples in the doc string
eg:
```python3
from aws_lambda_powertools.metrics import SingleMetric, MetricUnit
```
vs
```python3
from aws_lambda_powertools.metrics import single_metric, MetricUnit
```
**Checklist**

docs(metrics): Corrections to the docstrings code examples

---

aws_lambda_powertools/utilities/idempotency/persistence/base.py
tests/functional/idempotency/test_idempotency.py

Fix for `is_missing_idempotency_key` which  can raise a `TypeError: 'int' object is not iterable` 
for the follow code
```python3
BasePersistenceLayer.is_missing_idempotency_key(1000)
```
**Checklist**

fix(idempotency): TypeError when calling is_missing_idempotency_key with an int

---

docs/core/metrics.md

Correct the metrics code examples to use `MetricUnit.Count` when it was imported otherwise 
remove when not used in code sample 
**Checklist**

docs(metrics): Correct code examples in markdown

---

aws_lambda_powertools/logging/logger.py
aws_lambda_powertools/middleware_factory/exceptions.py
aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/batch/sqs.py
aws_lambda_powertools/utilities/idempotency/idempotency.py
aws_lambda_powertools/utilities/idempotency/persistence/dynamodb.py
docs/utilities/data_classes.md
docs/utilities/idempotency.md

Changes:
* Fix formatting for the api docs
* Correct the data classes and idempotent code examples in the docs
* Fix typo for `sampling rate`
**Checklist**

docs: Correct code examples

---

aws_lambda_powertools/logging/formatter.py
docs/core/logger.md
tests/functional/test_logger.py

Add `exception_name` to the logging
Example:
```python3
logger = Logger()
try:
raise ValueError("something went wrong")
except Exception:
logger.exception("Received an exception")
```
Would log out :
```json
{
"level": "ERROR",
"location": "<module>:4",
"message": "Received an exception",
"timestamp": "2020-08-28 18:11:38,886",
"service": "service_undefined",
"sampling_rate": 0.0,
"exception_name":"ValueError",
"exception": "Traceback (most recent call last):\n  File \"<input>\", line 2, in <module>\nValueError: something went wrong"
}
```
**Checklist**

feat(logging): Include exception_name

---

aws_lambda_powertools/utilities/idempotency/config.py
aws_lambda_powertools/utilities/idempotency/idempotency.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/318
Prefix the `hashed_idempotency_key` with the context function name:
```python
f"{context.function_name}#{self._generate_hash(data)}"
```
> **NOTE:** Rather than hash this prefix, I kept it in the clear to make debugging a little easier and I did not make 
this configurable, as this makes sense as the default
HOWEVER: You _MIGHT_  get edge cases where the function name has been changed while keeping an existing datastore
**Checklist**

feat(idempotent): Include function name in the idempotent key

---

aws_lambda_powertools/utilities/data_classes/appsync/resolver_utils.py
aws_lambda_powertools/utilities/data_classes/appsync/scalar_types_utils.py
tests/functional/appsync/test_appsync_resolver_utils.py

#324
Add support for [Scalar types in AWS AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html)
- Move existing scalar util functions in to scalar_types_utils.py
- Add support for timezone offset
- Add docstrings for scalar utils
- Update tests
Example usage:
```python3
>>> from aws_lambda_powertools.utilities.data_classes.appsync import scalar_types_utils
>>>
>>> scalar_types_utils.make_id()
'1e090fce-3798-40eb-b752-3664a39b0f34'
>>> scalar_types_utils.aws_date(timezone_offset=2)
'2021-03-14+02:00:00'
>>> scalar_types_utils.aws_time(timezone_offset=-1)
'23:33:58-01:00:00'
```
**Checklist**

feat(data-classes): Add appsync scalar_types_utils and add support for timezone offsets

---

aws_lambda_powertools/utilities/data_classes/common.py
docs/utilities/data_classes.md
tests/functional/test_lambda_trigger_events.py

Changes:
- Add property to access the `_data` dict
- Add more code examples for Cognito triggers showing how to set response values.
eg:
```python
from aws_lambda_powertools.utilities.data_classes.cognito_user_pool_event import (
DefineAuthChallengeTriggerEvent
)
def handler(event: dict, context) -> dict:
event: DefineAuthChallengeTriggerEvent = DefineAuthChallengeTriggerEvent(event)
if (
len(event.request.session) == 1
and event.request.session[0].challenge_name == "SRP_A"
):
event.response.issue_tokens = False
event.response.fail_authentication = False
event.response.challenge_name = "PASSWORD_VERIFIER"
elif (
len(event.request.session) == 2
and event.request.session[1].challenge_name == "PASSWORD_VERIFIER"
and event.request.session[1].challenge_result
): …
```

docs(data-classes): Add more cognito code examples

---

aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/base.py
aws_lambda_powertools/utilities/parameters/secrets.py
aws_lambda_powertools/utilities/parameters/ssm.py
tests/functional/test_utilities_parameters.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/131
Changes:
- Add new `force_fetch` to always fetch the latest value, even if there is a cached value
Example based on https://github.com/alexcasalboni/ssm-cache-python#complex-invalidation-based-on-signals
```python3
import os
from aws_lambda_powertools.utilities import parameters
class InvalidCredentials(Exception):
"""Raised when client get an invalid credentials error"""
class Client:
password = None
def configure(self, password):
self.password = password
def read_record(self):
"""Might raise an InvalidCredentials exception """
DB_PASS_PARAM = os.environ["DB_PASS_PARAM"]
db_client = Client()
db_client.configure(parameters.get_parameter(DB_PASS_PARAM))
def refresh_db_password(): …
```

feat(parameters): Add force_fetch option

---

docs/core/logger.md
docs/utilities/data_classes.md
docs/utilities/idempotency.md
docs/utilities/parameters.md

Surface new functionalities, enhancements, and refresh docs to better surface certain features previously hidden:
* **Parameters**: surface how to change cache TTL
* **Parameters**: add new force_fetch param
* **Parameters**: refresh to use new navigation
* **Idempotency**: add note on reusing a single table for idempotency state
* **Logger**: surface usage of new correlation_id and paths
* **Dataclasses**: remove additional note banners to ease reading
* **Dataclasses**: update AppSync Resolver to emphasize correlation, typos
**Checklist**

docs: surface new 1.12.0 features and enhancements 

---

aws_lambda_powertools/tracing/tracer.py

Typing for Tracer seems to be broken on PyCharm, see screenshot below:
The location of the `Returns` doc string is causing the PyCharm linter to thing that `Tracer` is  a tuple (possibly also due to the `_default_config` and `_config` before the `__init__` ? 
Changes:
* Move up `Returns` to just below the `Parameters`
* Add type hinting for `provider` 
* Add docstring for `provider`
**Checklist**

docs(tracer): Fix Tracer typing hinting for Pycharm

---

docs/index.md

Remove `Location` key from the `MyLambdaFunction` resource in the example template.yml.
According to the [ref docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html), `Layers` shouldn't be nested under `Location` 
This tripped me up so I thought I would offer to fix it.
**Checklist**

docs: Fix layers example template config

---

aws_lambda_powertools/logging/lambda_context.py
aws_lambda_powertools/logging/logger.py
aws_lambda_powertools/metrics/base.py
aws_lambda_powertools/metrics/metric.py
aws_lambda_powertools/metrics/metrics.py
aws_lambda_powertools/shared/functions.py
aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/batch/sqs.py
aws_lambda_powertools/utilities/data_classes/appsync/resolver_utils.py
aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
aws_lambda_powertools/utilities/data_classes/common.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/base.py
aws_lambda_powertools/utilities/parameters/dynamodb.py
aws_lambda_powertools/utilities/parameters/secrets.py
aws_lambda_powertools/utilities/parameters/ssm.py
aws_lambda_powertools/utilities/parser/types.py
aws_lambda_powertools/utilities/validation/base.py
aws_lambda_powertools/utilities/validation/validator.py
docs/utilities/data_classes.md
tests/functional/test_metrics.py

Changes:
- Correct typing to make mypy happier
- Correct highlighted lines
- fix(metrics): AttributeError raised when setting metadata_set
- fix(parser): Use sys.version_info to determine where we need typing_extensions
Before 
```
$ mypy aws_lambda_powertools
....
Found 126 errors in 29 files (checked 99 source files)
```
After 
```
$ mypy aws_lambda_powertools
....
Found 52 errors in 18 files (checked 99 source files)
```
and ignore missing imports:
```
Found 32 errors in 10 files (checked 99 source files)
```
**Checklist**

fix(metrics): AttributeError raised by MediaManager and Typing and docs

---

aws_lambda_powertools/tracing/tracer.py

#360
Changes:
- Type hint `lambda_handler` as a Union with and without `kwargs`
- Mark method params as required, when they are
- Type hint  `patch_modules` as a Unit of Tuple or List
**Checklist**

fix(tracer): Correct type hint for MyPy

---

Makefile

`pre-commit` runs additional checks that `make pr` does not perform like `trailing-whitespace`
Changes:
- Add `pre-commit` as a target in the Makefile
**Checklist**

build(pre-commit): Add pre-commit to `make pr`

---

aws_lambda_powertools/utilities/parser/models/__init__.py
aws_lambda_powertools/utilities/parser/models/s3_object_event.py
docs/utilities/parser.md
tests/functional/parser/test_s3 object_event.py

implements https://github.com/awslabs/aws-lambda-powertools-python/issues/361
also added missing imports in init file

feat(parser): Add S3 Object Lambda Event

---

aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
tests/functional/test_lambda_trigger_events.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/371
Add missing field `operationName` 
**Checklist**

fix(data-classes): Add missing operationName

---

aws_lambda_powertools/utilities/parser/models/s3.py
poetry.lock
pyproject.toml
tests/functional/parser/test_s3.py

**Issue #, if available:** #372
As described in the #372, `S3Model` should allow keys with 0 bytes. This PR upgrades Pydantic from 1.6 to 1.8, [which brings the new `NonNegativeInt` type](https://pydantic-docs.helpmanual.io/changelog/#v18-2021-02-26).
**Checklist**

fix(parser): S3Model support empty keys

---

aws_lambda_powertools/utilities/parameters/dynamodb.py
docs/utilities/parameters.md

This feature allows capturing to use this library also with dynamodb running locally with docker
**Checklist**

feat(parameter): add dynamodb_endpoint_url for local_testing

---

aws_lambda_powertools/utilities/idempotency/idempotency.py
tests/functional/idempotency/test_idempotency.py

Idempotent handler is currently returning `IdempotencyPersistenceLayerError` instead of the `IdempotencyKeyError`
**Checklist**

fix(idempotent): Correctly raise IdempotencyKeyError

---

poetry.lock
pyproject.toml

**Issue #, if available:** #383
X-Ray SDK 2.7.0 replaced `jsonpickle` with own implementation for serializing subsegments data. This breaks when there's an exception raised as per #383. 
This PR locks X-Ray SDK to 2.6.0 as it's the last working version until there's a fix.
**Checklist**

fix: lock X-Ray SDK to 2.6.0 due to regression

---

Makefile
poetry.lock
pyproject.toml

fix: downgrade poetry to 1.1.4

---

docs/core/event_handler.md
docs/core/logger.md
docs/core/tracer.md
docs/utilities/batch.md
docs/utilities/idempotency.md
docs/utilities/middleware_factory.md
docs/utilities/parameters.md
docs/utilities/parser.md
docs/utilities/validation.md

Changes:
- docs(batch): Remove archors for `sqs_batch_processor` and `PartialSQSProcessor`
- docs(idempotency): Fix link for `IdempotencyConfig`
- docs(paramters): Fix link for `AWS AppConfig`
- docs(tracer): Fix link highlight for `capture_lambda_handler`
- docs: Consitently format Key Features
**Checklist**

docs: Fix doc links and line highlights

---

docs/shared/validation_basic_eventbridge_event.json
docs/shared/validation_basic_jsonschema.py
docs/utilities/validation.md

**Issue #, if available:** #386
**Checklist**

docs(validator): include more complete examples & intro to JSON Schema

---

docs/core/event_handler/appsync.md
docs/index.md
docs/utilities/middleware_factory.md
docs/utilities/validation.md

Changes:
- Use target _blank for external links
- Correct some of the line highlighted in the examples
- Fix links to Tracer
**Checklist**

docs: Correct link targets and line highlights

---

docs/utilities/idempotency.md

**Issue #, if available:** #377
**Checklist**

docs(idempotency): add default table configuration for those not using IaC

---

docs/core/logger.md

docs(logger): add example on how to set UTC timestamp

---

docs/core/tracer.md

Fix line highlights in examples
**Checklist**

docs(tracer): Fix line highlighting

---

aws_lambda_powertools/utilities/validation/validator.py

**Issue #, if available:** #401
**Checklist**

fix(validator): event type annotation as any in validate fn

---

aws_lambda_powertools/metrics/metrics.py
docs/core/metrics.md
tests/functional/test_metrics.py

**Issue #, if available:** #406
**Checklist**
Persists two dimensions across all metrics, every Metrics instance throughout the codebase, and across all Lambda invocations.
```python
from aws_lambda_powertools import Metrics
from aws_lambda_powertools.metrics import MetricUnit
metrics = Metrics(namespace="ExampleApplication", service="booking")
metrics.set_default_dimensions(environment="prod", another="one")
@metrics.log_metrics
def lambda_handler(evt, ctx):
metrics.add_metric(name="SuccessfulBooking", unit=MetricUnit.Count, value=1)
```

feat: add support to persist default dimensions

---

poetry.lock
pyproject.toml

- https://github.com/aws/aws-xray-sdk-python/pull/284
- https://github.com/awslabs/aws-lambda-powertools-python/issues/383
**Checklist**

fix(deps): Bump aws-xray-sdk from 2.6.0 to 2.8.0

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
mkdocs.yml
tests/functional/event_handler/test_api_gateway.py

Change:
- Add new ResponseBuilder to replace the Tuple[Route, Response]
- Refactor code to be easier to maintain
- Fill in some docs and place holder notes for the main docs page
**Checklist**

refactor(event-handler): Add ResponseBuilder and more docs

---

aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/logger.py
aws_lambda_powertools/tracing/tracer.py
aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
aws_lambda_powertools/utilities/data_classes/appsync_resolver_event.py
aws_lambda_powertools/utilities/data_classes/event_bridge_event.py
aws_lambda_powertools/utilities/data_classes/s3_object_event.py
aws_lambda_powertools/utilities/data_classes/sns_event.py
aws_lambda_powertools/utilities/data_classes/sqs_event.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
docs/core/logger.md
tests/functional/test_metrics.py

For minor changes such as remapping keys, removing certain keys, etc., you will no longer have to implement a whole custom formatter from `BasePowertoolsFormatter`.
This PR introduces a public method `serialize` that is called after log record processing takes place, so customers don't have to reimplement extra keys, UTC support, X-Ray (if used), etc:
```python
from aws_lambda_powertools.logging.formatter import LambdaPowertoolsFormatter
from typing import Dict
class CustomFormatter(LambdaPowertoolsFormatter):
def serialize(self, log: Dict) -> str:
log["event"] = log.pop("message")
return self.json_serializer(log)
logger = Logger(service="example", logger_formatter=CustomFormatter())
logger.info("hello")
```
This PR also …

refactor: simplify custom formatter for minor changes

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
tests/functional/event_handler/test_api_gateway.py

https://github.com/awslabs/aws-lambda-powertools-python/pull/418
- Enum to match code style (PascalCase)
- Keep not found only in message return for security reasons
- Remove Tuple type of response to keep it simpler (Dict and Response only)
**Checklist**

refactor(event-handler): api gateway handler review changes

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
docs/core/event_handler/appsync.md
docs/core/logger.md
tests/functional/event_handler/test_api_gateway.py

**Checklist**
- ~~[x] Create sample infrastructure~~ 
- ALB has no support for CloudFormation for Lambda as target
**Minor implementation changes**
cc @michaelbrewer 

docs(api_gateway): new event handler for API Gateway and ALB

---

aws_lambda_powertools/utilities/parser/parser.py
docs/utilities/parser.md

When attempting to use the parse function we noticed we were getting
error messages like:
Value of type variable "Model" of "parse" cannot be "Type[UserModel]"
Further investigation (using the example shown at
https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#envelopes)
showed that the types were incorrect for the example. The function
signatures were expecting an instance of `Model`, however the example
(and code) seemeed to expect a `Type[Model]`.
Similarly the signatures were expecting an optional instance of an
Envelope, but the code allows for either an instance or a Type.
Finally, added a `TypeVar` for the decorator, specifying that the
event_parser` decorator returns the same type as the handler used.
Fix type signatures of parser.py
**Checklist** …

fix(parser): Improve types for parser.py

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

At the route level we should allow for `cors=None` which means that cors are enabled for this route when configured globally
Global Setting | Route Setting | Includes cors headers?
-- | -- | --
`app=ApiGatewayResolver()` | `@app.get("/cors", cors=True)` | Yes
`app=ApiGatewayResolver(cors=CORSConfig())` | `@app.get("/cors", cors=True)` | Yes
`app=ApiGatewayResolver()` | `@app.get("/no-cors", cors=False)` | No
`app=ApiGatewayResolver(cors=CORSConfig())` | `@app.get("/no-cors", cors=False)` | No
`app=ApiGatewayResolver()` | `@app.get("/no-cors")` | No
`app=ApiGatewayResolver(cors=CORSConfig())` | `@app.get("/cors")` | Yes
---
**Checklist**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

feat(event-handler): allow for `cors=None` setting

---

CHANGELOG.md
pyproject.toml

chore: bump to 1.15.0

---

docs/core/event_handler/api_gateway.md

Use the updated names for ProxyEventType which are now CamelCased.
**Checklist**

fix(docs): Use updated names for ProxyEventType

---

aws_lambda_powertools/logging/formatter.py
tests/functional/test_logger_powertools_formatter.py

**Issue #, if available:** N/A
This adjusts the default logging formatter (`LambdaPowertoolsFormatter`)
to handle non-structured logs with formatting, like:
```python
logger.info("foo %s", "bar")
```
This allows the formatter to be used in more situations, such as the
universal formatter for all log messages coming out of a system, even
libraries using the normal logging functionality, without explicit
support for aws-lambda-powertools.
If formatting is performed, this is taken as a hint that the value
probably isn't semantically JSON, even if it's syntactically valid as
JSON.
(I've called this a bug fix in the title but could be a 'feat' too, I guess?)
**Checklist**
**RFC issue #**: N/A
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(logger): Support .info("foo %s", "bar") formatting

---

aws_lambda_powertools/utilities/data_classes/__init__.py
aws_lambda_powertools/utilities/data_classes/code_pipeline_job_event.py
docs/utilities/data_classes.md
tests/events/codePipelineEvent.json
tests/events/codePipelineEventData.json
tests/functional/test_data_classes.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/414
Add support for CodePipeline Job event data class
Code example based on the docs: 
- [Sample Python function that uses an AWS CloudFormation template](https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html#actions-invoke-lambda-function-samples)
```python3
from aws_lambda_powertools.utilities.data_classes import CodePipelineJobEvent
logger = Logger()
def lambda_handler(event, context):
"""The Lambda function handler
If a continuing job then checks the CloudFormation stack status
and updates the job accordingly.
If a new job then kick of an update or creation of the target
CloudFormation stack.
"""
event: …
```

feat(data-classes): support for code pipeline job event

---

aws_lambda_powertools/utilities/data_classes/common.py
tests/functional/test_data_classes.py

Code example:
```python3
def lambda_handler(event: dict, context):
event = APIGatewayProxyEvent(event)
body: str = event.decoded_body
print(body)
```
Where the event is:
```json
{
"body": "W3siaWQiOjEsIm5hbWUiOiJDb21wYW55IE9uZSJ9LHsiaWQiOjIsIm5hbWUiOiJDb21wYW55IFR3byJ9XQo=",
"isBase64Encoded": true
}
```
Print statement:
```json5
[{"id":1,"name":"Company One"},{"id":2,"name":"Company Two"}]
```
- Based on a tweet: https://twitter.com/donkersgood/status/1390292767662825473
**Checklist**

feat(data-classes): decode base64 encoded body

---

.github/mergify.yml

This change has been made by @heitorlessa from https://mergify.io config editor.

chore: update mergify to require approval on dependabot

---

aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py
tests/functional/test_data_classes.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/461
Changes:
Example usage:
```python3
from aws_lambda_powertools.utilities.data_classes import event_source, DynamoDBStreamEvent
from aws_lambda_powertools.utilities.data_classes.dynamo_db_stream_event import AttributeValueType, AttributeValue
from aws_lambda_powertools.utilities.typing import LambdaContext
@event_source(data_class=DynamoDBStreamEvent)
def lambda_handler(event: DynamoDBStreamEvent, context: LambdaContext):
for record in event.records:
key: AttributeValue = record.dynamodb.keys["id"]
if key == AttributeValueType.Number:
assert key.get_value == key.n_value
print(key.get_value)
elif key == AttributeValueType.Map:
assert key.get_value == key.map_value
print(key.get_value)
```
Where …

feat(data-classes): add AttributeValueType to DynamoDBStreamEvent

---

aws_lambda_powertools/logging/logger.py
docs/core/logger.md
tests/functional/test_logger.py

**Checklist**
```python
logger = Logger(service="payment")
@logger.inject_lambda_context(clear_state=True)
def handler(event, context):
if event.get("special_key"):
logger.append_keys(debugging_key="value")
logger.info("Collecting payment")
```

feat(logger): add option to clear state per invocation

---

docs/stylesheets/extra.css
mkdocs.yml

Something like this would be easier on the eyes when most of the time
you are coding in dark mode style themes

docs: enable dark mode switch

---

aws_lambda_powertools/utilities/validation/base.py
tests/functional/validator/conftest.py
tests/functional/validator/test_validator.py

**Issue #, if available:** #496
JSONSchema Draft 7 has support for custom built-in formats like `date-time`. This PR fixes a malformed input to the upstream JSON validator (`fastjsonschema`) which cannot differentiate between custom format and custom built-in formats.
If no custom formats are explicitly passed we default to a Dict when passing that as input to `fastjsonschema`. This leads to the right fallback mechanism in the upstream validator to search for built-in custom formats.
Example JSON schema field that triggered it:
```json
"message": {
"$id": "#/properties/message",
"type": "string",
"format": "date-time",
"title": "The message",
"examples": ["hello world"],
},
```
**Checklist**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(validator): handle built-in custom formats correctly

---

docs/core/tracer.md

**Issue #, if available:** #476
This PR adds an additional scenario on when to disable auto-capture response - >64K responses
**Checklist**

docs(tracer): additional scenario when to disable auto-capture

---

docs/index.md

**Issue #, if available:** #355 #2
**Checklist**

docs: add Layers example for Serverless framework & CDK

---

.chglog/CHANGELOG.tpl.md
.chglog/config.yml
CHANGELOG.md
pyproject.toml

chore: bump 1.17.1

---

aws_lambda_powertools/utilities/data_classes/appsync/scalar_types_utils.py
tests/functional/test_data_classes.py

#503
Set the formatted output to include milliseconds
fixes #503
**Checklist**
Potentially a breaking change if expecting only seconds.
---

fix(data-classes): include milliseconds in scalar types

---

aws_lambda_powertools/event_handler/__init__.py
aws_lambda_powertools/event_handler/api_gateway.py
aws_lambda_powertools/event_handler/content_types.py
aws_lambda_powertools/event_handler/exceptions.py
tests/functional/event_handler/test_api_gateway.py

- https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/8
Pairs with https://github.com/awslabs/aws-lambda-powertools-python/pull/507
Changes:
- Add base ServiceError exception for rest api service errors
- BaseRequestError for 400s
- UnauthorizedError for 401s
- NotFoundError for 404s
- InternalServerError for 500s
Example usage for a unauthorized error
```python3
@app.route(method="GET", rule="/unauthorized-error")
def unauthorized_error():
raise UnauthorizedError("Unauthorized")
```
will return:
```json5
{
"statusCode": 401,
"headers": {
"Content-Type": "application/json"
},
"body: "{'statusCode':401,''message':'Unauthorized'}"
}
```
> NOTE: This is related to https://github.com/awslabs/aws-lambda-powertools-python/pull/507
**Checklist**
By …

feat(api-gateway): add common service errors

---

aws_lambda_powertools/utilities/feature_toggles/__init__.py
aws_lambda_powertools/utilities/feature_toggles/appconfig_fetcher.py
aws_lambda_powertools/utilities/feature_toggles/configuration_store.py
aws_lambda_powertools/utilities/feature_toggles/exceptions.py
aws_lambda_powertools/utilities/feature_toggles/schema.py
aws_lambda_powertools/utilities/feature_toggles/schema_fetcher.py
aws_lambda_powertools/utilities/parameters/appconfig.py
tests/functional/feature_toggles/test_feature_toggles.py
tests/functional/feature_toggles/test_schema_validation.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/470
First poc branch. Has only pure python, no pydantic. 
Missing: md doc , schema validation implementstion (currently has a todo commengt there),  more tests for exception cases
usage example can be found at this gist: https://gist.github.com/risenberg-cyberark/903bc41079218bb719c98321f8e6152b

feat(feat-toggle): New simple feature toggles rule engine (WIP)

---

aws_lambda_powertools/utilities/parser/models/apigw.py
tests/events/apiGatewayProxyEvent_noVersionAuth.json
tests/functional/test_data_classes.py

**Issue #531 **
Change to APIGatewayProxyEventModel to make "version" Optional
Change to APIGatewayEventRequestContext to make "authorizer" Optional
**Checklist**

fix(parser): Make ApiGateway version, authorizer fields optional

---

aws_lambda_powertools/tracing/tracer.py

**Issue #, if available:** #465
**Checklist**
- [See limitation](https://github.com/awslabs/aws-lambda-powertools-python/pull/529#issuecomment-881891898)

fix(tracer): mypy generic to preserve decorated method signature

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

**Issue #, if available:** #520
This fixes a regex bug that used a greedy pattern ending with incorrect path resolution, as any path after a pattern would be included in the argument.
Excerpt:
```python
@app.get("/accounts/<account_id>")
def get_account(account_id: str):
print(f"Account ID ({account_id}) would be 123")
@app.get("/accounts/<account_id>/source_networks")
def get_account_networks(account_id: str):
print(f"Account ID ({account_id}) would be 123/source_networks")
```
In this example, say we have a GET request as `/accounts/123` and another as `/accounts/123/source_networks`, we'd have the following effect prior to this fix:
Function | Regex | Effective account_id value
------------------------------------------------- | …

fix(api-gateway): non-greedy route pattern regex

---

Makefile
aws_lambda_powertools/utilities/feature_toggles/__init__.py
aws_lambda_powertools/utilities/feature_toggles/appconfig_fetcher.py
aws_lambda_powertools/utilities/feature_toggles/configuration_store.py
aws_lambda_powertools/utilities/feature_toggles/exceptions.py
aws_lambda_powertools/utilities/feature_toggles/schema.py
aws_lambda_powertools/utilities/feature_toggles/schema_fetcher.py
aws_lambda_powertools/utilities/idempotency/persistence/dynamodb.py
mypy.ini
tests/functional/feature_toggles/test_feature_toggles.py
tests/functional/feature_toggles/test_schema_validation.py

Changes:
- Add missing test coverage
- Fix some MyPy error
- Use NumPy docstrings
- Use *Error naming convention for exceptions (`ConfigurationException` vs `ConfigurationError`)
- Add pretty output for `make mypy` and remove from the `mypy.ini`, to fix issues with PyCharm. 
**Checklist**

refactor(feature-toggles): Code coverage and housekeeping

---

docs/core/logger.md

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/23
**Checklist**

docs(logger): document new get_correlation_id method

---

docs/core/event_handler/api_gateway.md
docs/index.md

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/8
**Checklist**

docs(api-gateway): document new HTTP service error exceptions

---

.chglog/CHANGELOG.tpl.md
CHANGELOG.md
pyproject.toml

chore: bump 1.18.0

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

**Issue #, if available:** #550
**Checklist**

fix(apigw): route regression for non-word chars 1st take

---

aws_lambda_powertools/utilities/data_classes/common.py
tests/functional/test_data_classes.py

- #544
Use `decoded_body` for the body in `json_body`. This will allow for a json string that is base64 encoded to be decoded and parsed in one go.
**Checklist**

feat(data-classes): decode json_body if based64 encoded

---

aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/secrets.py
aws_lambda_powertools/utilities/parameters/ssm.py

- https://github.com/awslabs/aws-lambda-powertools-python/issues/561
Expose the following parameters at the top level interface:
- max_age
- raise_on_transform_error
**Checklist**

feat(params): expose high level max_age, raise_on_transform_error

---

aws_lambda_powertools/utilities/feature_flags/appconfig.py
aws_lambda_powertools/utilities/feature_flags/base.py
aws_lambda_powertools/utilities/feature_flags/feature_flags.py
aws_lambda_powertools/utilities/feature_flags/schema.py

- Demark optional value
- Correct doctstring indents for pdoc3
- Correct example code type to `python`
**Checklist**

docs(feature-toggles): correct docs and typing

---

.github/release-drafter.yml
aws_lambda_powertools/utilities/feature_flags/feature_flags.py

**Issue #, if available:** #563
**Checklist**

refactor(feature-flags): add debug for all features evaluation"

---

Makefile

Seems like poetry 1.1.7 has resolved a bug which forced us to use 1.1.4
**Checklist**

fix(deps): bump poetry to latest

---

aws_lambda_powertools/utilities/feature_flags/feature_flags.py
aws_lambda_powertools/utilities/feature_flags/schema.py
tests/functional/feature_flags/test_feature_flags.py
tests/functional/feature_flags/test_schema_validation.py

Schema changes of condition keywords. 
- Add IN action instead of contains
- Add NOT_IN action
**Checklist**

feat(feature flags): Add not_in action and rename contains to in

---

docs/utilities/parameters.md

#562 
Added subsection under "Utilities > Parameters > Advanced > Deserializing values with transform parameter" titled "Infer transform from parameter suffix with `get_multiple()`" to document auto transform behaviour.
**Checklist**

docs(parameters): auto-transforming values based on suffix

---

docs/utilities/feature_flags.md

Current CDK example has indent errors and some special characters (`<U+200B>`) and corrected `json.dumps`
**Checklist**

fix(feature-toggles): correct cdk example

---

README.md
docs/core/event_handler/api_gateway.md
docs/core/event_handler/appsync.md
docs/core/logger.md
docs/core/metrics.md
docs/core/tracer.md
docs/index.md
docs/utilities/batch.md
docs/utilities/data_classes.md
docs/utilities/feature_flags.md
docs/utilities/idempotency.md
docs/utilities/middleware_factory.md
docs/utilities/parameters.md
docs/utilities/parser.md
docs/utilities/validation.md

Changes:
- Correct the readme me link to feature flags correct location is `https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/feature_flags/`
- Fix some of the json examples in `feature_flags.md`
- run [markdownlint](https://github.com/DavidAnson/markdownlint) against all of the `*.md` files
> Unfortunately alot of white space changes, so in the diff `Hide whitespace changes` make help hide the noise
**Checklist**

chore(docs): correct markdown based on markdown lint

---

aws_lambda_powertools/exceptions/__init__.py
aws_lambda_powertools/shared/jmespath_utils.py
aws_lambda_powertools/utilities/feature_flags/appconfig.py
aws_lambda_powertools/utilities/validation/exceptions.py
aws_lambda_powertools/utilities/validation/validator.py
pyproject.toml
tests/functional/idempotency/conftest.py

chore(shared): fix cyclic import & refactor data extraction fn

---

aws_lambda_powertools/event_handler/api_gateway.py
aws_lambda_powertools/utilities/data_classes/appsync_authorizer_event.py

- Rename `match` to `match_results`
- fix Docstrings for optionals.
**Checklist**

refactor(event_handler): match to match_results; 3.10 new keyword

---

aws_lambda_powertools/utilities/parser/models/apigw.py
aws_lambda_powertools/utilities/parser/models/cloudwatch.py
aws_lambda_powertools/utilities/parser/models/kinesis.py
aws_lambda_powertools/utilities/parser/models/sns.py

- https://github.com/awslabs/aws-lambda-powertools-python/issues/611
Set `allow_reuse=True` for all of the pydantic validators, so the docs can render.
**Checklist**

chore(api-docs): enable allow_reuse to fix the docs

---

aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
tests/functional/event_handler/test_api_gateway.py

- https://github.com/awslabs/aws-lambda-powertools-python/issues/621
Automatically strip out "/" + `stage` when building the request path.
**Checklist**
This is potentially a break change, if mapping against the stage name

fix(api-gateway): strip stage name from request path

---

aws_lambda_powertools/utilities/data_classes/kinesis_stream_event.py
tests/functional/test_data_classes.py

**Issue https://github.com/awslabs/aws-lambda-powertools-python/issues/617
adding `data_as_bytes` helper to `KinesisStreamRecordPayload` as described in linked issue
**Checklist**

feat(data-classes): data_as_bytes prop KinesisStreamRecordPayload

---

aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
docs/utilities/data_classes.md
tests/functional/data_classes/test_api_gateway_authorizer.py

**Issue #, if available:** #620
**Checklist**
-----
[View rendered docs/utilities/data_classes.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/authorizer-typos/docs/utilities/data_classes.md)

docs(data-classes): make authorizer concise; use enum

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Add support for codespaces to make it easier for contributors to get started.
Features:
- Setups up dev dependencies and pre-commit hooks
- Installs vscode extension
- Test explorer
- etc..
**Checklist**

chore: setup codespaces

---

docs/core/event_handler/api_gateway.md
docs/utilities/data_classes.md
docs/utilities/idempotency.md

Minor whitespace fixes.
**Checklist**
-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/gyft/aws-lambda-powertools-python/blob/chore/markdown-linter/docs/core/event_handler/api_gateway.md)
[View rendered docs/utilities/data_classes.md](https://github.com/gyft/aws-lambda-powertools-python/blob/chore/markdown-linter/docs/utilities/data_classes.md)
[View rendered docs/utilities/idempotency.md](https://github.com/gyft/aws-lambda-powertools-python/blob/chore/markdown-linter/docs/utilities/idempotency.md)

chore: markdown linter fixes

---

aws_lambda_powertools/utilities/idempotency/persistence/base.py
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py

**Issue #, if available:** #638
**Checklist**

fix(idempotency): sorting keys before hashing

---

pyproject.toml

**Issue #, if available:** #634
Adds THIRD-PARTY-LICENSES to the tarball.
Following #635, this adds (hopefully) the THIRD-PARTY-LICENSES to the tarball. Apparently, Poetry [doesn't use](https://stackoverflow.com/questions/64654860/replacing-manifest-in-with-pyproject-toml) Manifest anymore which is why it didn't work in the first try.
**Checklist**

chore(license): Add THIRD-PARTY-LICENSES to pyproject.toml

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
tests/functional/event_handler/test_api_gateway.py

**Issue #, if available: #646**
After removing path prefixes, allow an empty path to return `"/"` so that it will match a normal routing rule.
**Checklist**

fix: Fix issue with strip_prefixes

---

docs/utilities/data_classes.md

Rename `to_dict` to `addict`
**Checklist**
-----
[View rendered docs/utilities/data_classes.md](https://github.com/gyft/aws-lambda-powertools-python/blob/fix/app-sync-doc-typo/docs/utilities/data_classes.md)

fix(data-classes): use correct asdict funciton

---

.pylintrc
aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
docs/utilities/data_classes.md
tests/functional/data_classes/test_api_gateway_authorizer.py

> **NOTE:** We might want to explain "This will also pollute Lambda metrics with errors, also causing cold starts since it's not handled." in the docs to.
Changes:
- Clean up the internal logic for `APIGatewayAuthorizerResponse` 
- Update the internal docs to include a new `DENY_ALL_RESPONSE`
- Add missing property `usageIdentifierKey` for Rest API responses only
- Add `from_route_arn` to build APIGatewayAuthorizerResponse from an `arn`
- Add a relaxed pylintrc configuration for those use have this installed
```python
from aws_lambda_powertools.utilities.data_classes import event_source
from aws_lambda_powertools.utilities.data_classes.api_gateway_authorizer_event import (
DENY_ALL_RESPONSE,
APIGatewayAuthorizerRequestEvent,
APIGatewayAuthorizerResponse, …
```

refactor(data-classes): clean up internal logic for APIGatewayAuthorizerResponse

---

aws_lambda_powertools/utilities/validation/base.py
aws_lambda_powertools/utilities/validation/exceptions.py
tests/functional/validator/test_validator.py

Current implementation will just build a message from the `JsonSchemaValueException` like:
```
'Failed schema validation. Error: data must contain [\'message\', \'username\'] properties, Path: [\'data\'], Data: {\'message\': \'hello_world\'}'
```
Which is not presentable and missing some of the data elements.  This change updates `SchemaValidationError` to include more data elements from `JsonSchemaValueException`
- validation_message :  Containing human-readable information what is wrong (e.g. `data.property[index] must be smaller than or equal to 42`)
- name : name of a path in the data structure (e.g. `data.property[index]`)
- path: `path` as an array in the data structure (e.g. `['data', 'property', 'index']`),
- value : The invalid value
- definition : The …

feat(validator): include missing data elements from a validation error

---

aws_lambda_powertools/utilities/idempotency/persistence/dynamodb.py
tests/functional/idempotency/conftest.py

**Issue #, if available:** #693
Use `ExpressionAttributeNames` in `DynamoDBPersistenceLayer` `_put_record` call to to `table.put_item`.
**Checklist**

fix(idempotency): use ExpressionAttributeNames in DynamoDBPersistenceLayer _put_record

---

docs/index.md

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-python/issues/684
Currently the documentation provides example of installing the deploying
the SAR app using various frameworks.
This commit extend the list by providing a Terraform example.
**Checklist**
-----
[View rendered docs/index.md](https://github.com/DanyC97/aws-lambda-powertools-python/blob/fix-684-terraform-docs-example/docs/index.md)

docs: Terraform reference for SAR Lambda Layer

---

aws_lambda_powertools/utilities/batch/sqs.py
aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/dynamodb.py
aws_lambda_powertools/utilities/parameters/secrets.py
aws_lambda_powertools/utilities/parameters/ssm.py
docs/utilities/batch.md
docs/utilities/idempotency.md
docs/utilities/parameters.md

**Issue #, if available:** #704
Updated parameters and batch utilities to allow custom boto3 session to be passed. Standardized documentation of this functionality for idempotency, parameters and batch utilities.
**Checklist**
-----
[View rendered docs/utilities/batch.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/feat/allow_custom_boto_sessions/docs/utilities/batch.md)
[View rendered docs/utilities/idempotency.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/feat/allow_custom_boto_sessions/docs/utilities/idempotency.md)
[View rendered docs/utilities/parameters.md](https://github.com/awslabs/aws-lam …

feat: boto3 sessions in batch, parameters & idempotency

---

aws_lambda_powertools/utilities/feature_flags/feature_flags.py
aws_lambda_powertools/utilities/feature_flags/schema.py
docs/utilities/feature_flags.md
tests/functional/feature_flags/test_feature_flags.py
tests/functional/feature_flags/test_schema_validation.py

Added new conditions for contains that clarify what they are testing.
**Checklist**
**RFC issue #699**:
-----
[View rendered docs/utilities/feature_flags.md](https://github.com/gwlester/aws-lambda-powertools-python/blob/feature-699/docs/utilities/feature_flags.md)

feat(feature-flags): improve "IN/NOT_IN"; new rule actions

---

aws_lambda_powertools/utilities/feature_flags/feature_flags.py
tests/functional/feature_flags/test_feature_flags.py

fix(feature-flags): rules should evaluate with an AND op

---

aws_lambda_powertools/logging/logger.py
aws_lambda_powertools/utilities/feature_flags/appconfig.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
aws_lambda_powertools/utilities/jmespath_utils/__init__.py
aws_lambda_powertools/utilities/jmespath_utils/envelopes.py
aws_lambda_powertools/utilities/validation/validator.py
docs/utilities/idempotency.md
docs/utilities/jmespath_functions.md
tests/functional/feature_flags/test_feature_flags.py
tests/functional/idempotency/conftest.py

**Issue #, if available:** #661
This exposes an internal utility in Lambda Powertools to extract and deserialize JSON data using JMESPath w/ custom functions.
This will allow customers to **a)** reduce their boilerplate in extracting and decoding portions of their JSON objects, **b)** quickly extract JSON objects from popular event sources without resorting to documentation, and **c)** bring their own deserializers to recursively and conditionally decode data in any format.
```python
from aws_lambda_powertools.utilities.jmespath_utils import extract_data_from_envelope
from aws_lambda_powertools.utilities.typing import LambdaContext
def handler(event: dict, context: LambdaContext):
payload = extract_data_from_envelope(data=event, envelope="powertools_json(body)")
customer = …
```

feat: expose jmespath powertools functions

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

Add Router class to ApiGatewayResolver
**Issue #, if available: #644**
Add a `Router` class to be used as a proxy for `ApiGatewayResolver`.  The class is able to at as a placeholder for the app instance and collect routes to later be applied; it includes all the functionality of current routes.
To access query strings or headers the original `event` and `context` are made available as `router.current_event` and `router.lambda_context` respectively.  Also, to improve performance of a function which uses an endpoint with multiple methods, it offers a slight variation of the `route()` method's signature allowing a `list`/`tuple`.
app/main.py:
```python
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler.api_gateway import ApiGatewayResolver
from …
```

feat(apigateway): add Router to allow large routing composition

---

docs/index.md

After discussing with Alex and Heitor on this [tweet](https://twitter.com/sandro_vol/status/1446340381298282498) and in DMs I've added a section on how to add `aws-lambda-powertools-python` in an existing Amplify project.
Just documentation changes
**Checklist**
-----
[View rendered docs/index.md](https://github.com/AlessandroVol23/aws-lambda-powertools-python/blob/docss/public-arn-amplify-project/docs/index.md)

docs: add amplify-cli instructions for public layer

---

aws_lambda_powertools/utilities/idempotency/persistence/dynamodb.py
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py

**Issue #694**
Add new optional parameters, `key_attr_value` and `sort_key_attr`, to DynamoDBPersistenceLayer. If `sort_key_attr` is set, then DynamoDBPersistenceLayer will use a composite primary key with the _partition key_ set to a static value, defaults to `powertools#idempotency`, and the _sort key_ set to the hashed idempotency key.
**Checklist**

improv: Support a composite primary key in DynamoDBPersistenceLayer

---

poetry.lock
pyproject.toml

Fix issue with gh actions failing to build on python 3.9.8 due to old version of black.
**Checklist**

fix: change supported python version from 3.6.1 to 3.6.2, bump black

---

docs/utilities/idempotency.md

**Issue #, if available:** #694
Update documentation to reflect new feature supporting composite primary keys for DynamoDB in idempotency utility.
**Checklist**
-----
[View rendered docs/utilities/idempotency.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/docs/idempotency_sortkey_update/docs/utilities/idempotency.md)

docs(idempotency): add support for DynamoDB composite keys

---

aws_lambda_powertools/logging/correlation_paths.py

**Issue #, if available:** #767
```python
from aws_lambda_powertools.logging import correlation_paths
logger = Logger(service="payment")
@logger.inject_lambda_context(correlation_id_path=correlation_paths.ALB)
def handler(event, context):
logger.debug(f"Correlation ID => {logger.get_correlation_id()}")
logger.info("Collecting payment")
```
**Checklist**

feat(logger): add ALB correlation ID support

---

aws_lambda_powertools/utilities/parser/models/apigw.py
aws_lambda_powertools/utilities/parser/models/apigwv2.py
tests/functional/parser/test_apigw.py
tests/functional/parser/test_apigwv2.py

**Issue #, if available:** #797
Parser incorrectly expected `body` to always be non-empty; this addresses it.
**Actual event tested to repro #797**
```json
{
"body": null,
"resource": "/users",
"path": "/users",
"httpMethod": "GET",
"headers": {
"Accept": "*/*",
"CloudFront-Forwarded-Proto": "https",
"CloudFront-Is-Desktop-Viewer": "true",
"CloudFront-Is-Mobile-Viewer": "false",
"CloudFront-Is-SmartTV-Viewer": "false",
"CloudFront-Is-Tablet-Viewer": "false",
"CloudFront-Viewer-Country": "NL",
"Host": "a1c2k0n4x4.execute-api.eu-west-1.amazonaws.com",
"User-Agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)",
"Via": "2.0 b619a16f6f8fe9793bf642d2a8434284.cloudfront.net (CloudFront)",
"X-Amz-Cf-Id": "sj5uo2ZyuF8WvtxH6IYxHMQFHCuMWaD-xE5T-7WFZR28Jz-Kp4Zvsw==", …
```

fix(parser): body/QS can be null or omitted in apigw v1/v2

---

mkdocs.yml

Changing to Ubuntu type font to improve reading 
**Checklist**

docs: use higher contrast font

---

docs/core/event_handler/appsync.md

**Issue #, if available:** #776
**Checklist**
-----
[View rendered docs/core/event_handler/appsync.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/appsync-router/docs/core/event_handler/appsync.md)

docs(appsync): add new router feature

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
tests/functional/event_handler/test_api_gateway.py

**Issue #, if available:** #837
Allow a list (or tuple) of methods to be passed to the `ApiGatewayResolver.route` method, to match the functionality in `Router.route`
**Checklist**

fix(apigateway): allow list of HTTP methods in route method

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
tests/functional/event_handler/test_api_gateway.py

**Issue #, if available:** #834
Enable access to parent api resolver class from child router classes. Example:
app.py
```python
...
app = ApiGatewayResolver()
app.include_router(users.router, prefix="/users") # prefix 
def lambda_handler(event: Dict, context: LambdaContext):
return app.resolve(event, context)
```
users.py
```python
...
router = Router()
@router.get("/users/")
def get_users() -> Dict:
router.api_resolver.custom_functionality()
return {"message": "success"}
```
**Checklist**

feat(apigateway): access parent api resolver from router

---

aws_lambda_powertools/tracing/tracer.py
tests/unit/test_tracing.py

**Issue #, if available:** #850
Before this feature, you'd only filter traces for cold start invocations.
**Checklist**

fix(tracer): add warm start annotation (ColdStart=False)

---

docs/core/event_handler/api_gateway.md

Current version does not work when deployed
- https://github.com/awslabs/aws-lambda-powertools-python/issues/835
Fixes the sample layout for multiple file project
**Checklist**
-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/gyft/aws-lambda-powertools-python/blob/doc-updated-layout/docs/core/event_handler/api_gateway.md)

docs(apigateway): fix sample layout provided

---

poetry.lock
pyproject.toml

- https://github.com/awslabs/aws-lambda-powertools-python/pull/860
- https://github.com/awslabs/aws-lambda-powertools-python/pull/859
- https://github.com/awslabs/aws-lambda-powertools-python/pull/853
- https://github.com/awslabs/aws-lambda-powertools-python/pull/825
Current version of regex library (2021.4.4) does not include a mac arm64 variant.
This causes black to fail on Apple Silicon
Other libraries would also be upgraded as part of this like:
- bandit to 1.7.1
- boto3/botocore to 1.20.17
- coverage to 6.2
- flake8-bugbear to 21.11.29
**Checklist**

chore(deps): support arm64 when developing locally

---

aws_lambda_powertools/utilities/idempotency/base.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py

- #855
Include the callable function name in the generated idempotent key
**Checklist**

fix(idempotency): include decorated fn name in hash

---

aws_lambda_powertools/metrics/metric.py

* [Maintenance: address top papercuts #857](https://github.com/awslabs/aws-lambda-powertools-python/issues/857)
Simply update type return for `metrics.metric.single_metric`.
**Checklist**

fix(metrics): explicit type to single_metric ctx manager

---

aws_lambda_powertools/metrics/metric.py
aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
tests/functional/test_data_classes.py

- #870 
`self._data["response"].setdefault("claimsOverrideDetails", {})` does not work, if `claimsOverrideDetails` was set to `null` in the json event (or `None` in the parsed Python)
**Checklist**

fix(event-sources): handle claimsOverrideDetails set to null

---

aws_lambda_powertools/metrics/metric.py
aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/base.py
tests/functional/test_utilities_parameters.py

**Issue #, if available:**: 
Fix return type and handling transform value as str instead of bytes
**Checklist**
No breaking changes.  Introduces no new exception handling and would fix batch handling of more than 10 records.
**No RFC**:

fix(parameters): appconfig transform and return types

---

aws_lambda_powertools/utilities/parser/models/alb.py
aws_lambda_powertools/utilities/parser/models/apigw.py
aws_lambda_powertools/utilities/parser/models/apigwv2.py
aws_lambda_powertools/utilities/parser/models/cloudwatch.py
aws_lambda_powertools/utilities/parser/models/dynamodb.py
aws_lambda_powertools/utilities/parser/models/event_bridge.py
aws_lambda_powertools/utilities/parser/models/kinesis.py
aws_lambda_powertools/utilities/parser/models/s3.py
aws_lambda_powertools/utilities/parser/models/s3_object_event.py
aws_lambda_powertools/utilities/parser/models/sns.py
aws_lambda_powertools/utilities/parser/models/sqs.py
docs/utilities/parser.md

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-python/issues/857
This PR allows MyPy to not trigger an error when overriding payload types in built-in models provided by Parser, as described: https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#extending-built-in-models
**Scenario**: There are cases where you want to provide your own Model while retaining access to metadata information about the event. Previously, when using MyPy, this would cause a type override error since payload fields would only support what's expected, not a custom model as docs suggest for non-MyPy customers.
```python
from aws_lambda_powertools.utilities.parser import parse, BaseModel
from aws_lambda_powertools.utilities.parser.models import EventBridgeModel …
```

fix(parser): mypy support for payload type override as models

---

aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
aws_lambda_powertools/utilities/data_classes/common.py
tests/events/apiGatewayProxyEventPrincipalId.json
tests/functional/test_data_classes.py

Changes:
- contract APIGatewayEventAuthorizer from the authorizer data
- add test cases for the additional fields that can optional be in the authorizer dict
- Update DictWrapper to allow for a default in `get`
**Checklist**

fix(event-sources): Pass authorizer data to APIGatewayEventAuthorizer

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

- https://github.com/awslabs/aws-lambda-powertools-python/issues/899
```python3
app = ApiGatewayResolver()
@app.exception_handler(SomeKindOfError)
def handle_error(ex: SomeKindOfError):
print(f"request path is '{app.current_event.path}'")
return Response(
status_code=418,
content_type=content_types.TEXT_HTML,
body=str(ex),
)
@app.not_found()
def handle_not_found(exc: NotFoundError):
return Response(status_code=404, content_type=content_types.TEXT_PLAIN, body="I am a teapot!")
@app.exception_handler(ServiceError)
def service_error(ex: ServiceError):
logger.debug(f"Log out sensitive stuff: {ex.msg}")
return Response(
status_code=ex.status_code,
content_type=content_types.APPLICATION_JSON,
body="CUSTOM ERROR FORMAT",
)
@app.get("/my/path")
def call_with_error() -> …
```

feat(apigateway): add exception_handler support

---

aws_lambda_powertools/utilities/parser/models/kinesis.py
tests/functional/parser/test_kinesis.py

**Issue #, if available:** #858 
Kinesis Sequence Number was mistakenly set as `int` and Parser (Pydantic) coerces to `int`, this silently fails the new Batch Utility when reporting partial failure.
cc @ran-isenberg 
**Checklist**

fix(parser): kinesis sequence number is str, not int

---

aws_lambda_powertools/utilities/parser/envelopes/base.py
aws_lambda_powertools/utilities/parser/parser.py
aws_lambda_powertools/utilities/parser/types.py

When using parse function with an envelope, Mypy doesn't allow setting an explicit type as `parse` returns a `Model` while an envelope parse could return various types ranging from List[Model], Dict[str, Model], List[Optional[Model], and this can grow over time as more event types are defined too.
This PR uses type function overload to ensure `parse` continues to return a `Model` when no envelope is used, and when an envelope is used it'll propagate a generic type allowing an explicit type to be set at runtime.
If you don't set an explicit type when using `parse` with envelope, Mypy will detect as `Any` since MyPy can't have a generic return type in this case.
This uses a sample valid SNS payload as per the issue with an empty payload and with non-empty payload. …

fix(parser): overload parse when using envelope

---

.pre-commit-config.yaml
aws_lambda_powertools/utilities/batch/__init__.py
aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/batch/exceptions.py
docs/utilities/batch.md
tests/functional/test_utilities_batch.py
tests/functional/utils.py

**Issue #, if available:** #858
Implements new Batch Processor following the [new built-in partial response handling](https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/) for Lambda SQS, DynamoDB Stream, and Kinesis Data Streams. 
**Checklist**
**Tasks to be created in separate PR to ease reviewing**
**As a decorator**
```python
from aws_lambda_powertools.utilities.batch import batch_processor, BatchProcessor, EventType
from aws_lambda_powertools.utilities.data_classes.sqs_event import SQSRecord
processor = BatchProcessor(event_type=EventType.SQS) # or, EventType.KinesisDataStreams, EventType.DynamoDB
def record_handler(record: SQSRecord): # or DynamoDBRecord, KinesisStreamRecord
return "success" …
```

feat(batch): new BatchProcessor for SQS, DynamoDB, Kinesis

---

aws_lambda_powertools/utilities/batch/__init__.py
aws_lambda_powertools/utilities/batch/base.py
aws_lambda_powertools/utilities/batch/exceptions.py
aws_lambda_powertools/utilities/parser/parser.py
pyproject.toml
tests/functional/idempotency/test_idempotency.py
tests/functional/test_utilities_batch.py

Changes:
- ~~`child_exceptions` should be a tuple~~ EDIT: Fix type instead
- remove unecessary `else` statements
- add `pragma: no cover` for overload functions
- add test for an invalid DynamoDBPersistenceLayer
**Checklist**

chore: minor housekeeping before release

---

docs/core/event_handler/api_gateway.md
mkdocs.yml

**Issue #, if available:** #898
**Checklist**
-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/exception-handler-apigw/docs/core/event_handler/api_gateway.md)

docs(apigateway): add new not_found feature

---

aws_lambda_powertools/shared/functions.py

**Issue #, if available:** Fixes #906
Removes dependency on distutils.
**Checklist**

fix(warning): future distutils deprecation

---

aws_lambda_powertools/utilities/data_classes/active_mq_event.py
aws_lambda_powertools/utilities/data_classes/code_pipeline_job_event.py
aws_lambda_powertools/utilities/data_classes/common.py
aws_lambda_powertools/utilities/data_classes/kinesis_stream_event.py
aws_lambda_powertools/utilities/data_classes/rabbit_mq_event.py
tests/functional/data_classes/test_amazon_mq.py
tests/functional/test_data_classes.py

- #844
A micro optimization to cache the parsed json within the event source data class
**Checklist**

feat(event-sources): cache parsed json in data class

---

aws_lambda_powertools/tracing/tracer.py
tests/unit/test_tracing.py

- https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/35
```python3
from aws_lambda_powertools import Tracer
tracer = Tracer()
tracer.ignore_endpoint(hostname="ec2.amazon.com") 
tracer.ignore_endpoint(hostname="*.sensitive.com", urls=["/password", "/credit-card"]) 
def ec2_api_calls():
return "suppress_api_responses"
@tracer.capture_lambda_handler
def handler(event, context):
for x in long_list:
ec2_api_calls()
```
**Checklist**

feat(tracer): ignore tracing for certain hostname(s) or url(s)

---

aws_lambda_powertools/utilities/idempotency/base.py
aws_lambda_powertools/utilities/idempotency/persistence/base.py
docs/utilities/idempotency.md
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py
tests/functional/utils.py

Add support for serialization of python dataclasses, but checking if `__dataclass_fields__` exists and calling `dataclasses.asdict`. This happens early on in the idempotency work flow.
```python
from dataclasses import dataclass
from aws_lambda_powertools.utilities.idempotency import (
DynamoDBPersistenceLayer, IdempotencyConfig, idempotent_function)
dynamodb = DynamoDBPersistenceLayer(table_name="idem")
config =  IdempotencyConfig(
event_key_jmespath="messageId",  # see Choosing a payload subset section
use_local_cache=True,
)
@dataclass
class OrderItem:
sku: str
description: str
@dataclass
class Order:
item: OrderItem
order_id: int
@idempotent_function(data_keyword_argument="order", config=config, persistence_store=dynamodb)
def process_order(order: Order): …
```

feat(idempotency): support dataclasses & pydantic models payloads

---

README.md

I'm a huge fan of Appsync, GraphQL, and Single Table Design. Looking at the examples listed on the README.md, I couldn't find anything on that. So I created a sample Graphql API, which I think might also help others get up and running with `aws-lambda-powertools` and appsync.
I simply added a Sample Graphql API for a Nanny booking Platform to the Examples section of the README.md. The Repo is well documented, with illustrations.
**Checklist**
* [x ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

docs: Added GraphQL Sample API to Examples section of README.md

---

aws_lambda_powertools/event_handler/api_gateway.py
aws_lambda_powertools/shared/functions.py
aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
aws_lambda_powertools/utilities/data_classes/common.py
aws_lambda_powertools/utilities/idempotency/exceptions.py
aws_lambda_powertools/utilities/idempotency/idempotency.py
tests/functional/event_handler/test_api_gateway.py
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py
tests/functional/test_shared_functions.py

- https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/65
Changes:
- Allow for `@app.not_found()` decorator
- Add docstrings and typing to `strtobool`
- Add code coverage for  `strtobool`
- Minor docstring typos
- Add test for DynamoDBPersistenceLayer with a `sort_key_attr`
**Checklist**

fix(apigateway): support @app.not_found() syntax & housekeeping

---

aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py
tests/functional/test_data_classes.py

- #928
Return for `None` for null types:
Example: 
```json5
{
"Records": [
{
...
"dynamodb": {
"OldImage": {
...
"Message": {
"S": "New item!"
},
"Id": {
"N": "101"
}
},
"Keys": {
"Id": {
"N": "101"
}
},
"NewImage": {
...
"Message": {
"NULL": true
},
"Id": {
"N": "101"
}
},
}
}
]
}
```
Below `null_value` and `get_value` would have returned `True`, and now they return None.
```python3
from aws_lambda_powertools.utilities.data_classes import event_source
from aws_lambda_powertools.utilities.data_classes.dynamo_db_stream_event import (
DynamoDBStreamEvent,
)
@event_source(data_class=DynamoDBStreamEvent)
def handler(event: DynamoDBStreamEvent, context):
record = next(event.records)
message_value = record.dynamodb.new_image.get("message")
assert …
```

fix(event-sources): handle dynamodb null type as none, not bool

---

docs/core/event_handler/api_gateway.md
docs/core/event_handler/appsync.md
docs/core/logger.md
docs/core/metrics.md
docs/core/tracer.md
docs/index.md
docs/stylesheets/extra.css
docs/utilities/batch.md
docs/utilities/data_classes.md
docs/utilities/feature_flags.md
docs/utilities/idempotency.md
docs/utilities/jmespath_functions.md
docs/utilities/middleware_factory.md
docs/utilities/parameters.md
docs/utilities/parser.md
docs/utilities/typing.md
docs/utilities/validation.md

**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-python/issues/917
Throughout the documentation we had a bit of inconsistency around
admonitions.
As such we added few rules to keep the consistency which will improve
the UX:
* we should use `???+` instead of `!!!` so we can have a collapse block
(default open)
* for admonitions with default title, we should write the description
on a new line
* for admonitions which has a custom title as well as a description, we
should adhere to the format `<admonitions type>: <custom title>`.
E.g - for a tip admonitions with a custom title "Did you know?" and
description of "Powertools is a brilliant library"
```
???+ tip "Tip: Did you know?"
Powertools is a brilliant library
```
**Checklist**
By submitting …

docs: consistency around admonitions and snippets

---

docs/core/tracer.md

**Issue #, if available:** #910
Documents new `ignore_endpoint` feature in Tracer.
```python title="Ignoring certain HTTP endpoints from being traced"
from aws_lambda_powertools import Tracer
tracer = Tracer()
tracer.ignore_endpoint(hostname="ec2.amazon.com")
tracer.ignore_endpoint(hostname="*.sensitive.com", urls=["/password", "/credit-card"])
def ec2_api_calls():
return "suppress_api_responses"
@tracer.capture_lambda_handler
def handler(event, context):
for x in long_list:
ec2_api_calls()
```
**Checklist**
-----
[View rendered docs/core/tracer.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/tracer-ignore- …

docs(tracer): new ignore_endpoint feature

---

aws_lambda_powertools/logging/utils.py
docs/core/logger.md
tests/functional/test_logger_utils.py

**Issue #, if available: https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/40 
This feature allows customers to clone Powertools Logger configuration like level & handler to any registered Python loggers - exclusion, inclusion-only are also supported.

feat(logger): clone powertools logger config to any Python logger

---

docs/utilities/batch.md

**Issue #, if available:** Notified via Powertools Slack by KimL (thank you!!)
**Checklist**
-----
[View rendered docs/utilities/batch.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/batch-example-typo/docs/utilities/batch.md)

docs(batch): fix typo in context manager keyword

---

aws_lambda_powertools/utilities/parameters/appconfig.py

**Issue #, if available:** NA
fix _get of appconfig parameter utility documentation
**Checklist**

fix(parameters): appconfig internal _get docstrings

---

README.md

**Issue #, if available:** https://awslabs.github.io/aws-lambda-powertools-typescript/latest/
Add link to typescript version
**Checklist**
-----
[View rendered README.md](https://github.com/gyft/aws-lambda-powertools-python/blob/doc-typescript-link/README.md)

docs(homepage): link to typescript version

---

aws_lambda_powertools/event_handler/api_gateway.py
aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
aws_lambda_powertools/utilities/data_classes/appsync_resolver_event.py
aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py
aws_lambda_powertools/utilities/data_classes/s3_object_event.py
aws_lambda_powertools/utilities/data_classes/sqs_event.py

It's been a while since i scanned through the data classes for typos and improvements.
Changes:
- Use correct wording: `built-in`, `its`, `sign in`, `all the` and `case-sensitive`
- Modern use of `super()`
- Use `resource.lstrip("/")` instead of `resource[:1] == "/"` for readability to remove leading "/" that isn't allowed when constructing an authorizer response object
**Checklist**

fix(data-classes): docstring typos and clean up

---

docs/core/logger.md

Fix closure of python code block
Tiny change in the docs to fix a missing block closure in the markdown
**Checklist**
-----
[View rendered docs/core/logger.md](https://github.com/mozz100/aws-lambda-powertools-python/blob/patch-1/docs/core/logger.md)

docs(logger): fix code block syntax in FAQ

---

docs/core/event_handler/api_gateway.md
docs/core/event_handler/appsync.md
docs/tutorial/idempotency.md
docs/tutorial/index.md
mkdocs.yml

**Issue #, if available:** #857
Changes Event Handler ApiGateway title to REST API, and AppSync to GraphQL API while keeping URL the same. Enables navigation indexes feature and move tutorial to `tutorial/index.md` to keep navigation while allowing for growth - additional tutorials as customers request.
**Checklist**
-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/improve-navigation/docs/core/event_handler/api_gateway.md)
[View rendered docs/core/event_handler/appsync.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/improve-na …

docs(nav): make REST and GraphQL event handlers more explicit

---

docs/utilities/batch.md

This is a small change to the documentation, fixing an extra iteration over processed_messages in batch processor.
**Checklist**
* [X PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)
-----
[View rendered docs/utilities/batch.md](https://github.com/j2clerck/aws-lambda-powertools-python/blob/develop/docs/utilities/batch.md)

docs(batch): snippet typo on batch processed messages iteration

---

docs/utilities/batch.md

Variable `ddb_table` is not defined in the class. Updated with instance variable `self.ddb_table
`
**Checklist**
* [ :white_check_mark:] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ :white_check_mark:] Update docs
* [ :white_check_mark:] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)
-----
[View rendered docs/utilities/batch.md](https://github.com/thehananbhat/aws-lambda-powertools-python/blob/patch-1/docs/utilities/batch.md)

docs(batch): snippet typo in custom batch processor

---

docs/tutorial/index.md

Current paths to png images are broken, thus images are not visible in tutorial doc
**Checklist**
-----
[View rendered docs/tutorial.md](https://github.com/mploski/aws-lambda-powertools-python/blob/fix/tutorial-images/docs/tutorial.md)

docs(tutorial): fix path to images

---

aws_lambda_powertools/utilities/batch/base.py
tests/functional/test_utilities_batch.py

**Issue #, if available:** 966
Dictionary/List comprehensions can only contain one unique dict key (last one wins), as expected. Our logic for reporting multiple failures had a bug where we were constructing multiple dictionaries of `{"itemIdentifier": message}` instead of appending to a list - you can't solve this with a dictionary/list comprehension as the key is always static.
Thanks to @kimberlyamandalu for spotting this critical bug, since our tests somehow were only testing for a single fail record hence why we didn't spot it earlier (nor during review)
**Checklist**

fix(batch): report multiple failures

---

aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
tests/functional/data_classes/test_api_gateway_authorizer.py

When building a authorizer response we should allow for underscores in the resource
**Checklist**

fix(data-classes): underscore support in api gateway authorizer resource name

---

aws_lambda_powertools/logging/logger.py
tests/functional/test_logger.py

closes #947
```python3
@event_source(data_class=S3Event)
@log.inject_lambda_context(log_event=True)
def lambda_handler(event: S3Event, context: LambdaContext):
...
```
Changes:
- Add dict data from raw_event when available
**Checklist**

feat(logger): log_event support event data classes (e.g. S3Event)

---

aws_lambda_powertools/event_handler/api_gateway.py
docs/core/event_handler/api_gateway.md
tests/functional/event_handler/test_api_gateway.py

**Issue #, if available:** #972
This PR removes additional indentation when using `debug_mode`. While effective for local development it creates additional log events for CloudWatch Logs incurring additional charges; this breaks our tenets hence we revert.
**Before**
**After**
**Checklist**
-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/fix/event-handler-debug-mode/docs/core/event_handler/api_gateway.md)

fix(apigateway): remove indentation in debug_mode

---

docs/tutorial/index.md

Extra indent is triggering: "Unexpected indentation" for python from the sample docs. Fixed the indent as per previous samples.
**Checklist**
-----
[View rendered docs/tutorial/index.md](https://github.com/am1ru1/aws-lambda-powertools-python/blob/patch-1/docs/tutorial/index.md)

fix(docs): indentation in tutorial snippets

---

aws_lambda_powertools/event_handler/__init__.py
docs/tutorial/index.md

All links pointing to other internal sections (e.g. Tracer, Logger) and their respective sections were broken.
We also update Event Handler example (`ApiGatewayResolver`) to use the new specialized one `APIGatewayRestResolver` to give customers a first class experience on autocompleting available properties.
**Checklist**
-----
[View rendered docs/tutorial/index.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/tutorial-broken-links/docs/tutorial/index.md)

docs(tutorial): fix broken internal links

---

aws_lambda_powertools/logging/utils.py
tests/functional/test_logger_utils.py

#999 
The source_logger was not added correctly to the exclusions.
**Checklist**

fix(logger): exclude source_logger in copy_config_to_registered_loggers

---

docs/core/event_handler/appsync.md

**Issue #, if available:** #857
Small improvements to "Testing Your Code" section in of graphql event handlers doc. Made example more relevant to a real application rather than borrowing our own example test, and added an example for async tests.
**Checklist**
-----
[View rendered docs/core/event_handler/appsync.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/docs/async_testing_example/docs/core/event_handler/appsync.md)

docs(event-handler): improve testing section for graphql

---

docs/utilities/parameters.md

**Issue #, if available:** #1009
Add "Testing your code" section to the documentation for parameters utility.
**Checklist**
-----
[View rendered docs/utilities/parameters.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/docs/testing_parameters/docs/utilities/parameters.md)

docs(parameters): add testing your code section

---

docs/core/event_handler/api_gateway.md
docs/core/event_handler/appsync.md
docs/tutorial/index.md
docs/utilities/feature_flags.md

- https://github.com/awslabs/aws-lambda-powertools-python/issues/1013
- fix line number highlights
- fix missing imports
- fix syntax error
- fix indents
- fix example code rendering
**Checklist**
-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/gyft/aws-lambda-powertools-python/blob/fix-docs/docs/core/event_handler/api_gateway.md)
[View rendered docs/tutorial/index.md](https://github.com/gyft/aws-lambda-powertools-python/blob/fix-docs/docs/tutorial/index.md)

docs: fix syntax errors and line highlights

---

aws_lambda_powertools/utilities/batch/base.py
tests/functional/test_utilities_batch.py

closes #1021
Changes:
- Add failing test
- Add part of `_prepare` we should also clear the `exceptions` list, so that cold starts and warm starts behave the same.
**Checklist**

fix(batch): bugfix to clear exceptions between executions

---

aws_lambda_powertools/event_handler/__init__.py
docs/core/event_handler/api_gateway.md

- #1018
- Related to #1004
Changes:
- Fix import statements for `CORSConfig` and `Response` in docs (for current versions) 
- Add CORSConfig to __init__.py for ease of use (to allow for this shortcut in future versions) 
**Checklist**

fix(event_handler): docs snippets, high-level import CorsConfig

---

aws_lambda_powertools/metrics/base.py
tests/functional/test_metrics.py

Per the [EMF spec](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_target), metric value arrays must not have more than 100 elements. This PR ensures that metrics are serialized when a single metric collects 100 values in addition to the existing behavior of serializing when 100 metrics are collected.
Note: as far as I can see, this same change needs to be brought to the other Powertools languages as well. I'm not equipped nor have the skill to submit a PR for any language other than Python.
**Checklist**

fix(metrics): flush upon a single metric 100th data point

---

docs/utilities/parser.md

Fix the built-in model that is responsible for parsing events of API Gateway Proxy v1 to Lambda. Someone write that the built-in model is [`aws_lambda_powertools.utilities.data_classes.APIGatewayProxyEvent`](https://github.com/awslabs/aws-lambda-powertools-python/blob/22f8b9a7f47a2a4682c6f3f03536ac848ae7dc0d/aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py#L73), but, in fact, the right model for parsing using `event_parser` is [`aws_lambda_powertools.utilities.parser.models.APIGatewayProxyEventModel`](https://github.com/awslabs/aws-lambda-powertools-python/blob/22f8b9a7f47a2a4682c6f3f03536ac848ae7dc0d/aws_lambda_powertools/utilities/parser/models/apigw.py#L79).
When we try to use the wrong one (`APIGatewayProxyEvent`) in `event_parser`, it results in an error since …

docs(parser): APIGatewayProxyEvent to APIGatewayProxyEventModel

---

mkdocs.yml

**Issue #, if available:** N/A but discussed directly with maintainers
This PR adds [the plugin](https://squidfunk.github.io/mkdocs-material/reference/diagrams/) that allows to use mermaid diagrams in the MKDocs documentation as discussed internally.
**Note**: the diagram above is provided only as an aid for review, it is not part of the actual commit.
Additionally I also updated the year in copyright notice that is in the footer of the docs to the correct year (it was still 2021).
**Checklist**

docs(plugin): add mermaid to create diagram as code

---

aws_lambda_powertools/logging/formatter.py
aws_lambda_powertools/logging/logger.py
docs/core/logger.md
tests/functional/test_logger.py

**Issue #, if available:** #1042
This ensures custom logger formatters receive Lambda context keys and their state can be cleared upon each invocation when using `clear_state`. This PR also takes into account those using `log_record_order` with custom formatters, if the state is ever cleared.
The reason we use an `abstractmethod` is to ensure all functionalities (as docs suggested) will work for the ~1% of customers creating highly customized loggers that can work in more than Lambda environments. We initially thought in having warnings but given this is a bug behavior and the extreme edge case, it makes it worthwhile to enforce it early and improve documentation on use cases for `LambdaPowertoolsFormatter` (common, no change required) vs `BasePowertoolsFormatter` (edge case). …

fix(logger): ensure state is cleared for custom formatters

---

aws_lambda_powertools/logging/utils.py
tests/functional/test_logger_utils.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/1073
Ensure external loggers doesn't propagate logs to root logger by disabling Propagate attribute. Previously event was emitted in external logger ( with powertools handler) and in root handler IF propagation was set to True. This change ensure log is only emitted by external logger handler.
Also, during debugging noticed that we don't exclude `aws_lambda_powertools`  from handler modification since this is root powertools package we might treat it as internal package and skip applying powertools logger handler. @heitorlessa  please correct me if I'm wrong here 
**Checklist**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(logger): Ensure external loggers doesn't propagate logs

---

aws_lambda_powertools/logging/utils.py
tests/functional/test_logger_utils.py

https://github.com/awslabs/aws-lambda-powertools-python/issues/1073
Ensure proper loggers are excluded from config propagation
**Checklist**

fix(logger-utils): regression on exclude set leading to no formatter

---

aws_lambda_powertools/logging/formatter.py
tests/functional/test_logger.py

**Issue #, if available:** #1084 #1087
When using `clear_state=True`, standard logging keys like `level, location, timestamp` are no longer being preserved. This is a regression introduced in 1.25.3, when fixing custom formatters for clear_state behaviour. Our tests weren't robust enough for clear_state - this PR adds additional tests to cover gaps we had.
Issue was that when `clear_state=True` was used, the default keys (level, location, timestamp) weren't being re-added as part of a new `clear_state` method for LambdaPowertoolsFormatter implemented in 1.25.3, hence the regression.
```
{
"level": "%(levelname)s",
"location": "%(funcName)s:%(lineno)d",
"timestamp": "%(asctime)s",
}
```
**Checklist**
By submitting this pull request, I confirm that you can use, modify, …

fix(logger): clear_state regression on absent standard keys

---

aws_lambda_powertools/utilities/idempotency/base.py
tests/functional/idempotency/conftest.py
tests/functional/idempotency/test_idempotency.py
tests/functional/idempotency/utils.py
tests/functional/utils.py

This protects against functions that inadvertently change the incoming event data
Switch to using a deep copy of data. Without this, we've seen two documents written for one function invocation that (inadvertently) mutated the event data:
* An _initial_ document with a hashed idempotency key _based on the original payload_ that will be stuck in INPROGRESS and has no return data
* A _second_ document with a hashed idempotency key _based on the mutated payload_ with status COMPLETED and the correct return value
Happy to add a test if there is an appetite for this change.
**Checklist**

fix(idempotency): pass by value on idem key to guard inadvert mutations

---

aws_lambda_powertools/logging/formatter.py
tests/functional/test_logger.py

**Issue #, if available:** #1084
When using `clear_state=True`, overriden formats for standard logging keys like `location` and `timestamp` was being overriden with the default formats.  Overriding the formats are explained in the docs like this:
```python
date_format = "%m/%d/%Y %I:%M:%S %p"
location_format = "[%(funcName)s] %(module)s"
logger = Logger(service="payment", location=location_format, datefmt=date_format)
```
Issue was that when `clear_state=True` was used, the default keys were reset to their defaults (by the fix implemented in #1088). This fix saves the formatting keys on instantiation and uses those instead when `clear_state` is called.
**Checklist**
By submitting this pull request, I confirm that you can use, …

fix(logger): clear_state should keep custom key formats

---

aws_lambda_powertools/middleware_factory/factory.py

**Issue #, if available:** #1060 
This is two versions of typing `lambda_handler_decorator` more accurately for #1060, to ensure that middleware using it have a type. They end up with type `Callable[..., Any]` but that's better than nothing.
The first commit 937e6fe tries to be more accurate via overloads and protocols, but it doesn't work as written, and I cannot quite work out why. The errors below demonstrate the issues. It's potentially resolvable with 3.10's `ParamSpec` (I'm not sure `typing_extensions` depended upon for 3.8 and 3.8?):
<details><summary>Errors</summary>
```
aws_lambda_powertools/utilities/validation/validator.py:12:2: error: No overload variant of "lambda_handler_decorator" matches argument type "Callable[[Callable[..., Any], Union[Dict[Any, Any], str], Any, …
```

fix(middleware_factory): ret type annotation for handler dec

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

**Issue number:** #1098
Updated the `_UNSAFE_URI` constant to support whitespace in path parameter
User facing nothing changed
<details>
Checklist:
</details>

fix(api_gateway): allow whitespace in routes' path parameter

---

docs/utilities/parser.md

Issue, if available: #1078
Pydantic can be installed without binary files. This significantly
reduces the additional size it adds to the compressed Lambda packages
(down to 2MB from 25MB) at the expense of 30%-50% of its performance.
While at it I also updated the amount of megabyte Pydantic adds to the
package, as it wasn't clear if the stated number referred to compressed
or uncompressed package size and I couldn't reproduce the 75MB either
way.
**Checklist**
-----
[View rendered docs/utilities/parser.md](https://github.com/yomagroup/aws-lambda-powertools-python/blob/docs-pydantic-without-binary-files/docs/utilities/parser.md)

docs(install): instructions to reduce pydantic package size

---

poetry.lock
pyproject.toml

**Issue number:**
- #1138
NOTE: For testing purposes
But using Poetry [Multiple constraints dependencies](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) you can support both Python 3.6 and Python 3.7+ libraries
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged …

fix(deps): update jmespath marker to support 1.0 and py3.6

---

poetry.lock
pyproject.toml

**Issue number:**
#1147 
Removes JMESPath to allow downstream deps to solve this.
Removes JMESPath dependency from `pyproject.toml`
See issue (#1147)
<details>
Checklist:
</details>

fix(deps-dev): remove jmespath due to dev deps conflict 

---

.github/dependabot.yml

adds a ignore to dependabot to stop adding boto3 pull requests
Adds an ignore to dependabot for the boto3 module

fix(deps): ignore boto3 updates until needed

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

**Issue number:**
- #1152
Changes:
- Allow for event being of type 'BaseProxyEvent'
- Add test case
Code like this would no longer raise a type error
<details>
Checklist:
</details>

fix(event_handler): Allow for event_source support

---

aws_lambda_powertools/utilities/parameters/__init__.py
aws_lambda_powertools/utilities/parameters/base.py
docs/utilities/parameters.md
tests/functional/test_utilities_parameters.py

**Issue number:** #1092 
This introduces a new method in each Parameters provider called `clear_cache`, and a standalone function to clear cache across all providers that is useful for customers using higher level functions.
**Clearing cache for an individual parameters provider**
```python
import pytest
from src import app
@pytest.fixture(scope="function", autouse=True)
def clear_parameters_cache():
yield
app.ssm_provider.clear_cache() # This will clear SSMProvider cache
@pytest.fixture
def mock_parameter_response(monkeypatch):
def mockreturn(name):
return "mock_value"
monkeypatch.setattr(app.ssm_provider, "get", mockreturn)
def …
```

feat(parameters): add clear_cache method for providers

---

aws_lambda_powertools/utilities/batch/base.py

Just a simple typo I noticed while using the library.
<details>
Checklist:
</details>

fix(batch): missing space in BatchProcessingError message

---

aws_lambda_powertools/utilities/parameters/appconfig.py
aws_lambda_powertools/utilities/parameters/base.py
aws_lambda_powertools/utilities/parameters/dynamodb.py
aws_lambda_powertools/utilities/parameters/secrets.py
aws_lambda_powertools/utilities/parameters/ssm.py
docs/utilities/parameters.md
poetry.lock
pyproject.toml
tests/functional/test_utilities_parameters.py

**Fixes:** #1079
This adds a new `boto3_client` constructor parameter to the Parameters feature to unblock customers using [VPC endpoints](https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html).
~~I didn't add it to DynamoDB parameter because i'm not sure it's possible there. Fixed also the docs.~~ All clients have it now, and DynamoDB has a note in docstrings + type referring to Resource Client (high-level) not Client (low-level) like SSM, SecretsManager and AppConfig.
```python
import boto3
from aws_lambda_powertools.utilities import parameters
ssm = boto3.client("ssm", endpoint_url="custom_endpoint")
secrets = boto3.client("secretsmanager", …
```

feat(parameters): accept boto3_client to support private endpoints and ease testing

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/static_typing.yml
.github/auto_assign-issues.yml
.github/boring-cyborg.yml
.github/release-drafter.yml
.github/workflows/post_release.js
.github/workflows/publish.yml
.github/workflows/release-drafter.yml
MAINTAINERS.md

Issue number: #1076
Document describing who are the maintainers, processes to maintain this project, etc.
<details>
Checklist:
</details>
-----
[View rendered MAINTAINERS.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/new-maintainer …

docs(maintainers): initial maintainers playbook

---

aws_lambda_powertools/metrics/base.py
docs/core/metrics.md
tests/functional/test_metrics.py

**Issue number:** #1239
Lambda Powertools adds a `service` CloudWatch Metric Dimension on top of user-defined dimensions. If customers add 9 user-defined dimensions, Powertools were previously adding `service` dimension directly into the dictionary making EMF to not process these metrics - EMF is an async process managed by CloudWatch Logs and it fails silently, all validation must happen on the client side for any feedback.
This PR addresses our documentation stating that the limit is **8** and ensures our `service` dimension addition goes through the same user-defined dimension validation process.
If your change doesn't seem to apply, please leave them …

fix(metrics): raise SchemaValidationError for >8 metric dimensions

---

tests/functional/test_metrics.py

**Issue number:** #1239
In #1240, I repurposed the original test `test_exceed_number_of_dimensions` to account for `service` dimension, since the outcome would be the same (`SchemaValidationError`).
This PR reverts that test change, fix an old typo (`we we`), and adds a specific test `test_exceed_number_of_dimensions_with_service`.
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull …

chore(metrics): revert dimensions test before splitting

---

aws_lambda_powertools/event_handler/api_gateway.py
tests/functional/event_handler/test_api_gateway.py

**Issue number:** #1248
ALB doesn't follow [HTTP CORS Spec](https://fetch.spec.whatwg.org/#http-responses) and returns 502 when a body response is null. This PR returns an empty string to make it compliant.
<details>
Checklist:
</details>

fix(event-handler): body to empty string in CORS preflight (ALB non-compliant)

---

.github/workflows/python_docs.yml
.pre-commit-config.yaml
Makefile
docs/core/tracer.md
examples/tracer/src/capture_lambda_handler.py
examples/tracer/template.yaml

**Issue number:** #1009
This PR splits code snippets into a top-level `examples` folder. Formatting and linting (`make lint`) were adjusted to include `examples` folder. We also introduce [cfn-lint](https://github.com/aws-cloudformation/cfn-lint) within pre-commit hooks to selectively lint changed infra files within `examples` folder.
The only downside is that documentation needs to be rebuilt/rerun when example files are changed, as live change won't reflect files that are included.
We'll keep all examples under `examples` folder. Each feature will have its own source code that match what's in the documentation, followed by one or more infrastructure as code customers could use in the future.
**Example for Tracer**
```shell
examples
└── …
```

docs(tracer): split and lint code snippets

---

docs/core/logger.md
examples/logger/src/append_and_remove_keys.json
examples/logger/src/append_and_remove_keys.py
examples/logger/src/cloning_logger_config.py

**Issue number:** #1267
Document how users of the `Logger` can further enrich logs
Add additional FAQ question/answer.
n/a
-----
[View rendered docs/core/logger.md](https://github.com/kbakk/aws-lambda-powertools-python/blob/docs/improve-logger-keys-usage/docs/core/logger.md)

docs(logger): document enriching logs with logrecord attributes
