awslabs/aws-lambda-powertools-python

- .github/workflows/pythonpackage.yml
- python/setup.py
> feat: Add Python3.8 support

- Makefile
- docs/gatsby-config.js
- docs/package-lock.json
- docs/package.json
- docs/src/gatsby-theme-apollo-docs/components/header.js
*Issue #, if available:* #41 
Major fix from this PR has been implemented in DocSearch Algolia: https://github.com/algolia/docsearch-configs/pull/1998
Search results under /api were causing 404, and as we can't have rewrite/redirect in GitHub Pages it's best to update the crawler to prevent that from happening. 
> Docs: fix minor UX issues

- .github/release-drafter.yml
> feat: add release drafter

- .github/workflows/python_build.yml
> One or two sentences as a summary of what's being changed
Include security and complexity baseline checks in CI workflow
* ~~[ ] Update tests~~
* ~~[ ] Update docs~~
> feat: add security and complexity baseline #33

- docs/gatsby-browser.js
- docs/package-lock.json
- docs/package.json
- docs/src/config.js
This adds anonymized click stream to understand which sections are most popular. That will help us understand both areas we should double down too.
**Checklist**
> feat: docs anonymized page view

- CHANGELOG.md
- pyproject.toml
**Issue #, if available:** #97 #99
**Checklist**
> chore: bump to 1.1.0

- .github/workflows/python_docs.yml
> chore: trigger docs on new release

- .github/workflows/python_docs.yml
> chore: trigger docs on new release (#102)

- CHANGELOG.md
- pyproject.toml
> chore: bump version to 1.1.2

- pyproject.toml
> chore: bump to 1.1.3

- CHANGELOG.md
- pyproject.toml
> chore: bump version to 1.2.0

- CHANGELOG.md
- docs/content/core/logger.mdx
- pyproject.toml
> chore: bump to 1.6.0

- CHANGELOG.md
- pyproject.toml
> chore: bump to 1.6.1

- CHANGELOG.md
- pyproject.toml
> chore: bump to 1.7.0

- docs/content/dummy.md
- docs/yarn.lock
> chore: update docs dependencies

- docs/src/gatsby-theme-apollo-docs/components/page-content.js
**Issue #, if available:** #220 
This creates a new button on side bar pointing to the GitHub repository.
**Checklist**
> docs: add source code link in nav bar

- aws_lambda_powertools/utilities/parser/models/__init__.py
- aws_lambda_powertools/utilities/parser/models/s3.py
- docs/content/utilities/parser.mdx
- tests/events/s3EventGlacier.json
- tests/functional/parser/test_s3.py
feat: Add S3 lambda event support to Parser utility #224
Added schema files and tests to parser utility
> feat: Add S3 lambda event support to Parser utility #224

- docs/content/utilities/parser.mdx
Added missing documentation - sns & ses parser models
> docs: add missing parser models

- docs/content/utilities/parser.mdx
> chore: typo in parser docs

- CHANGELOG.md
- pyproject.toml
> chore: bump to 1.10.2

- CHANGELOG.md
- pyproject.toml
> chore: bump to 1.10.3

- CHANGELOG.md
- pyproject.toml
> chore: version bump to 1.10.4

- CHANGELOG.md
- pyproject.toml
> chore: version bump to 1.10.5

- aws_lambda_powertools/utilities/data_classes/__init__.py
- aws_lambda_powertools/utilities/data_classes/connect_contact_flow_event.py
- tests/events/connectContactFlowEventAll.json
- tests/events/connectContactFlowEventMin.json
- tests/functional/test_lambda_trigger_events.py
Added Amazon Connect lambda contact flow event for type hint support and ease of use.
Added two test events to test the added classes.
**Checklist**
> feat(data-classes): Add connect contact flow event

- docs/utilities/batch.md
**Issue #, if available:** #293
Adds new sub-section to instruct customers wanting to capture individual exceptions and send to Sentry.io.
**Checklist**
> docs(batch): add example on how to integrate with sentry.io

- aws_lambda_powertools/utilities/idempotency/idempotency.py
- docs/utilities/idempotency.md
- mkdocs.yml
- tests/functional/idempotency/test_idempotency.py
> docs(idempotency): tidy up doc before release

- docs/core/event_handler/appsync.md
- docs/shared/getting_started_schema.graphql
- mkdocs.yml
**Issue #, if available:** #356
**Checklist**
> docs: introduce event handlers utility section

- aws_lambda_powertools/logging/formatter.py
- docs/core/logger.md
**Issue #, if available:** #404
**Checklist**
> docs(logger): improvements extensibility & new features

- poetry.lock
- pyproject.toml
upgrade pydantic to 1.8.2
see issue at #436
> feat(parser): security issue in Pydantic #436

- .github/mergify.yml
> chore: enable mergify

- README.md
- mkdocs.yml
> docs: include new public roadmap

- docs/core/logger.md
**Issue #, if available:** #460
**Checklist**
> docs(logger): add FAQ for cross-account searches

- README.md
Add our awesome code coverage badge!
[![codecov.io](https://codecov.io/github/awslabs/aws-lambda-powertools-python/branch/develop/graphs/badge.svg)](https://app.codecov.io/gh/awslabs/aws-lambda-powertools-python)
**Checklist**
> docs(readme): add code coverage badge

- .github/workflows/python_build.yml
- pyproject.toml
Add support for Python 3.9: https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/
**Checklist**
> feat(general): support for Python 3.9

- MANIFEST.in
Includes the THIRD-PARTY-LICENSES file
Closes #634
**Checklist**
> chore(license): add third party license

- docs/index.md
- mkdocs.yml
@cakepietoast and I rewrote the Idioms tenet to better reflect recent changes like **1/** the upcoming Event Handler Router, and **2/** the new wave of customer who are long-term developers, SREs, data analysts and data scientists familiar with the language and practices but not necessarily Serverless.
This also helps us ensure new investments are more balanced such as Quickstarts, a potential Workshop, and a more opinionated quick start sample.
**Checklist**
-----
[View rendered docs/index.md](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/develop/docs/index.md)
> docs(tenets): update Idiomatic tenet to Progressive

- aws_lambda_powertools/logging/logger.py
- tests/functional/test_logger.py
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-python/issues/895
**Checklist**
> feat(logger): allow handler with custom kwargs signature

- mkdocs.yml
**Issue #, if available:** #889
**Checklist**
> docs: external reference to cloudformation custom resource helper

- docs/index.md
> Which issue number/url will this fix?
**Fixes:** #1134
Removes href from clipboard button, so Chrome customers can correctly copy Lambda Layer ARN values.
Gif demonstrating that the text should continue to work, and the clipboard button will no longer be a href
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on …
> docs(layer): remove link from clipboard button
